/**
 * Widget Manager — factory that spawns WindowAbject and WidgetAbject instances.
 *
 * WidgetManager is a thin factory. It spawns widget Abjects on the bus and
 * returns their AbjectIds. All rendering, input handling, and state management
 * lives in the widget Abjects themselves.
 *
 * Primary API (returns AbjectIds for direct message passing):
 *   createWindowAbject, destroyWindowAbject, create (batch widget factory),
 *   createVBox, createHBox, createNestedVBox, createNestedHBox,
 *   createScrollableVBox, createNestedScrollableVBox, createCanvas
 *
 * Legacy shim (for ScriptableAbjects generated by ObjectCreator):
 *   createWindow, destroyWindow, addWidget, updateWidget,
 *   removeWidget, getWidgetValue, widgetEvent
 */

import {
  AbjectId,
  AbjectMessage,
  InterfaceId,
} from '../core/types.js';
import { Abject, DEFERRED_REPLY } from '../core/abject.js';
import { require } from '../core/contracts.js';
import { request, event } from '../core/message.js';
import { Log } from '../core/timed-log.js';

const log = new Log('WidgetManager');
import { ModalDialog } from './modal-dialog.js';
import { WindowAbject } from './widgets/window-abject.js';
import { LabelWidget } from './widgets/label-widget.js';
import { ButtonWidget } from './widgets/button-widget.js';
import { TextInputWidget, TextInputWidgetConfig } from './widgets/text-input-widget.js';
import { TextAreaWidget, TextAreaWidgetConfig } from './widgets/text-area-widget.js';
import { CheckboxWidget, CheckboxWidgetConfig } from './widgets/checkbox-widget.js';
import { ProgressWidget, ProgressWidgetConfig } from './widgets/progress-widget.js';
import { DividerWidget } from './widgets/divider-widget.js';
import { SelectWidget, SelectWidgetConfig } from './widgets/select-widget.js';
import { CanvasWidget, CanvasWidgetConfig } from './widgets/canvas-widget.js';
import { TabBarWidget, TabBarConfig } from './widgets/tabbar-widget.js';
import { SliderWidget, SliderWidgetConfig } from './widgets/slider-widget.js';
import { ImageWidget, ImageWidgetConfig } from './widgets/image-widget.js';
import { ListWidget, ListWidgetConfig, ListItem } from './widgets/list-widget.js';
import { SplitPaneWidget, SplitPaneConfig } from './widgets/split-pane-widget.js';
import { WidgetAbject, WidgetConfig } from './widgets/widget-abject.js';
import { VBoxLayout } from './widgets/vbox-layout.js';
import { HBoxLayout } from './widgets/hbox-layout.js';
import { ScrollableVBoxLayout } from './widgets/scrollable-vbox-layout.js';
import { LayoutAbject, LayoutMargins } from './widgets/layout-abject.js';
import {
  WidgetType,
  WidgetStyle,
  Rect,
  ThemeData,
  MIDNIGHT_BLOOM,
} from './widgets/widget-types.js';

export type { WidgetStyle } from './widgets/widget-types.js';

const WIDGETS_INTERFACE: InterfaceId = 'abjects:widgets';

/**
 * WidgetManager — spawns window and widget Abjects, returns their IDs.
 */
export class WidgetManager extends Abject {
  private uiServerId?: AbjectId;
  private consoleId?: AbjectId;
  private defaultTheme: ThemeData = MIDNIGHT_BLOOM;
  private workspaceThemes: Map<string, { themeId: AbjectId; theme: ThemeData }> = new Map();
  private windowManagerId?: AbjectId;

  // Tracking spawned Abjects (Set<AbjectId>, NOT references — network transparent)
  private spawnedWindows: Set<AbjectId> = new Set();
  private spawnedWidgets: Set<AbjectId> = new Set();
  private orphanSweepTimer?: ReturnType<typeof setInterval>;
  // Maps windowId → surfaceId for raiseWindow support
  private windowSurfaces: Map<AbjectId, string> = new Map();
  // Maps objectId → workspaceId for compositor-level workspace filtering
  private objectWorkspaces: Map<AbjectId, string> = new Map();

  // Backward-compat shim: maps old string widget IDs → AbjectIds
  private shimWidgetMap: Map<string, AbjectId> = new Map();
  // Maps old windowId strings → WindowAbject AbjectIds
  private shimWindowMap: Map<string, AbjectId> = new Map();
  // Maps WindowAbject AbjectId → owning Abject
  private windowOwners: Map<AbjectId, AbjectId> = new Map();
  // Maps widget AbjectId → old-style string widget ID (for event translation)
  private widgetIdToShimId: Map<AbjectId, string> = new Map();
  // Maps widget AbjectId → window string ID (for event translation)
  private widgetToWindowShimId: Map<AbjectId, string> = new Map();
  // Maps widget AbjectId → parent WindowAbject AbjectId (for workspace tracing)
  private widgetToWindow: Map<AbjectId, AbjectId> = new Map();

  constructor() {
    super({
      manifest: {
        name: 'WidgetManager',
        description:
          'Widget factory — spawns WindowAbject and WidgetAbject instances on the bus. Primary API returns AbjectIds for direct message passing. Legacy shim for ScriptableAbjects. Use cases: build windowed apps with buttons/inputs/labels, create a canvas for games or visualizations, layout widgets in vertical/horizontal stacks.',
        version: '2.0.0',
        interface: {
            id: WIDGETS_INTERFACE,
            name: 'Widgets',
            description: 'Widget factory — spawns WindowAbject and WidgetAbject instances on the bus. ' +
              'Workflow: 1) createWindowAbject to get a window ID, 2) createVBox/createHBox to get a layout ID, ' +
              '3) batch-create widgets via create({ specs: [{ type: "label", windowId, text }, { type: "button", windowId, text }] }) which returns { widgetIds }, ' +
              '4) add widgets to layout via this.call(layoutId, "addLayoutChildren", { children: [{ widgetId, sizePolicy, preferredSize }] }), ' +
              '5) register for events via this.call(widgetId, "addDependent", {}), ' +
              '6) handle events in a "changed" handler: { aspect, value } where aspect is "click", "change", or "submit". ' +
              'Update widgets via this.call(widgetId, "update", { text: "new text" }). ' +
              'Get values via this.call(widgetId, "getValue", {}).',
            methods: [
              {
                name: 'createWindowAbject',
                description: 'Create a window and return its AbjectId. Example: const winId = await this.call(this.dep("WidgetManager"), "createWindowAbject", { title: "My Window", rect: { x: 100, y: 100, width: 400, height: 300 }, resizable: true })',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Window title' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height } — position and size' },
                  { name: 'zIndex', type: { kind: 'primitive', primitive: 'number' }, description: 'Z-index for stacking order', optional: true },
                  { name: 'chromeless', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, no title bar', optional: true },
                  { name: 'resizable', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, window is resizable', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'destroyWindowAbject',
                description: 'Destroy a window by its AbjectId and all its child widgets.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Window AbjectId to destroy' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'createVBox',
                description: 'Create a vertical box layout inside a window. Returns the layout AbjectId. Add children via this.call(layoutId, "abjects:layout", "addLayoutChild", { widgetId, sizePolicy: { vertical: "fixed" }, preferredSize: { height: 36 } }). Add spacers via this.call(layoutId, "abjects:layout", "addLayoutSpacer", {}).',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createHBox',
                description: 'Create a horizontal box layout inside a window. Returns the layout AbjectId. Add children via this.call(layoutId, "abjects:layout", "addLayoutChild", { widgetId, sizePolicy: { horizontal: "expanding" }, preferredSize: { width: 100, height: 36 } }).',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedVBox',
                description: 'Create a nested vertical box layout inside a parent layout. Returns the layout AbjectId. Pass autoSize: true when inside a ScrollableVBox so it auto-computes its preferred height from children.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'autoSize', type: { kind: 'primitive', primitive: 'boolean' }, description: 'Auto-compute preferred height from children (use inside ScrollableVBox)', optional: true },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedHBox',
                description: 'Create a nested horizontal box layout inside a parent layout. Returns the layout AbjectId. Pass autoSize: true when inside a ScrollableVBox so it auto-computes its preferred height from children.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'autoSize', type: { kind: 'primitive', primitive: 'boolean' }, description: 'Auto-compute preferred height from children (use inside ScrollableVBox)', optional: true },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createScrollableVBox',
                description: 'Create a scrollable vertical box layout inside a window. Returns the layout AbjectId. Content that overflows is clipped and scrollable via mouse wheel.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'autoScroll', type: { kind: 'primitive', primitive: 'boolean' }, description: 'Pin to bottom when new content is added (for chat/log views). Default false.', optional: true },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedScrollableVBox',
                description: 'Create a nested scrollable vertical box layout inside a parent layout. Returns the layout AbjectId.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'autoScroll', type: { kind: 'primitive', primitive: 'boolean' }, description: 'Pin to bottom when new content is added (for chat/log views). Default false.', optional: true },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createCanvas',
                description: 'Create a canvas drawing widget inside a window. Returns the canvas widget AbjectId. Draw to it via this.call(canvasId, "abjects:canvas", "draw", { commands: [...] }). Get size via this.call(canvasId, "abjects:canvas", "getCanvasSize", {}).',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'inputTargetId', type: { kind: 'primitive', primitive: 'string' }, description: 'AbjectId that receives input events (defaults to caller)', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'create',
                description: 'Create one or more widgets in a single request. Each spec has { type, windowId, ...typeSpecificProps }. Supported types: label, button, textInput, textArea, checkbox, progress, divider, select, tabBar, slider, image, list, splitPane. Returns { widgetIds: AbjectId[] } in same order as specs.',
                parameters: [
                  { name: 'specs', type: { kind: 'array', elementType: { kind: 'reference', reference: 'WidgetSpec' } }, description: 'Array of widget creation specs. Each spec needs at minimum: { type, windowId }. Additional props depend on type (e.g. text, style, placeholder, checked, options, tabs, etc.)' },
                ],
                returns: { kind: 'object', properties: { widgetIds: { kind: 'array', elementType: { kind: 'primitive', primitive: 'string' } } } },
              },
              {
                name: 'showConfirmDialog',
                description: 'Show a modal confirmation dialog with backdrop overlay. Returns true if confirmed, false if cancelled.',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Dialog title' },
                  { name: 'message', type: { kind: 'primitive', primitive: 'string' }, description: 'Dialog message' },
                  { name: 'confirmLabel', type: { kind: 'primitive', primitive: 'string' }, description: 'Confirm button label (default: "Confirm")', optional: true },
                  { name: 'cancelLabel', type: { kind: 'primitive', primitive: 'string' }, description: 'Cancel button label (default: "Cancel")', optional: true },
                  { name: 'destructive', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, confirm button uses destructive styling', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'destroyWindowsForOwner',
                description: 'Destroy all windows owned by a specific object',
                parameters: [
                  { name: 'ownerId', type: { kind: 'primitive', primitive: 'string' }, description: 'Owner object AbjectId' },
                ],
                returns: { kind: 'primitive', primitive: 'number' },
              },
              {
                name: 'setObjectWorkspace',
                description: 'Associate an object with a workspace. All surfaces owned by this object will be tagged with the workspace ID for compositor-level filtering.',
                parameters: [
                  { name: 'objectId', type: { kind: 'primitive', primitive: 'string' }, description: 'The object to tag' },
                  { name: 'workspaceId', type: { kind: 'primitive', primitive: 'string' }, description: 'The workspace ID' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'getObjectWorkspace',
                description: 'Get the workspace ID associated with an object, or null if not tagged.',
                parameters: [
                  { name: 'objectId', type: { kind: 'primitive', primitive: 'string' }, description: 'The object to query' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'registerWorkspaceTheme',
                description: 'Register a per-workspace Theme object so widgets in that workspace use the correct theme',
                parameters: [
                  { name: 'workspaceId', type: { kind: 'primitive', primitive: 'string' }, description: 'Workspace ID' },
                  { name: 'themeId', type: { kind: 'primitive', primitive: 'string' }, description: 'Theme object AbjectId' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'getDisplayInfo',
                description: 'Get display dimensions (proxied from UIServer)',
                parameters: [],
                returns: {
                  kind: 'object',
                  properties: {
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
              // Legacy shim methods for backward compatibility
              {
                name: 'createWindow',
                description: '[Legacy] Create a window and return a shim string ID',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Window title' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Window position and size' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'destroyWindow',
                description: '[Legacy] Destroy a window by shim string ID',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Window shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'addWidget',
                description: '[Legacy] Add a widget to a window by shim IDs',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Target window shim ID' },
                  { name: 'id', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget identifier' },
                  { name: 'type', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget type' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Widget position' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'updateWidget',
                description: '[Legacy] Update widget properties by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                  { name: 'updates', type: { kind: 'reference', reference: 'WidgetUpdates' }, description: 'Properties to update' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'removeWidget',
                description: '[Legacy] Remove a widget by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'getWidgetValue',
                description: '[Legacy] Get widget value by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
            ],
            events: [
              {
                name: 'widgetEvent',
                description: 'Widget interaction event (click, change, submit)',
                payload: { kind: 'reference', reference: 'WMWidgetEventPayload' },
              },
              {
                name: 'windowMoved',
                description: 'Window was dragged by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    x: { kind: 'primitive', primitive: 'number' },
                    y: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
              {
                name: 'windowResized',
                description: 'Window was resized by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
            ],
          },
        requiredCapabilities: [],
        providedCapabilities: [],
        tags: ['system', 'ui'],
      },
    });

    this.setupHandlers();
  }

  private setupHandlers(): void {
    this.on('createWindow', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, resizable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        resizable?: boolean;
      };
      return this.createWindow(msg.routing.from, title, rect, { chromeless, resizable, zIndex });
    });

    this.on('destroyWindow', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: string };
      return this.destroyWindow(msg.routing.from, windowId);
    });

    // Direct factory: create window, return AbjectId (not shim string)
    this.on('createWindowAbject', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, transparent, resizable, draggable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        transparent?: boolean;
        resizable?: boolean;
        draggable?: boolean;
      };
      return this.createWindowDirect(msg.routing.from, title, rect, { chromeless, transparent, resizable, draggable, zIndex });
    });

    // Direct factory: destroy window by AbjectId (not shim string)
    this.on('destroyWindowAbject', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: AbjectId };
      return this.destroyWindowDirect(windowId);
    });

    // ── Batch widget creation (unified create method) ──

    this.on('create', async (msg: AbjectMessage) => {
      const { specs } = msg.payload as {
        specs: Array<{
          type: string;
          windowId: AbjectId;
          rect?: Rect;
          text?: string;
          style?: WidgetStyle;
          placeholder?: string;
          masked?: boolean;
          wordWrap?: boolean;
          minLines?: number;
          maxLines?: number;
          monospace?: boolean;
          checked?: boolean;
          value?: number;
          options?: string[];
          selectedIndex?: number;
          tabs?: string[];
          min?: number;
          max?: number;
          step?: number;
          url?: string;
          fit?: 'contain' | 'cover' | 'fill';
          alt?: string;
          items?: ListItem[];
          searchable?: boolean;
          itemHeight?: number;
        }>;
      };
      if (!Array.isArray(specs)) {
        throw new Error(`WidgetManager.create: expected specs array, got ${typeof specs}`);
      }
      const widgetIds: AbjectId[] = [];
      for (const spec of specs) {
        const id = await this.createWidgetFromSpec(spec);
        widgetIds.push(id);
      }
      return { widgetIds };
    });

    // ── Layout factory methods ──

    this.on('createVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new VBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createHBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new HBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createNestedVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        autoSize?: boolean;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new VBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }), payload.autoSize);
    });

    this.on('createNestedHBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        autoSize?: boolean;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new HBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }), payload.autoSize);
    });

    this.on('createScrollableVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        autoScroll?: boolean;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new ScrollableVBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        autoScroll: payload.autoScroll,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createNestedScrollableVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        autoSize?: boolean;
        autoScroll?: boolean;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new ScrollableVBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        autoScroll: payload.autoScroll,
        margins: payload.margins,
        spacing: payload.spacing,
      }), payload.autoSize);
    });

    // ── Canvas widget factory ──

    this.on('createCanvas', async (msg: AbjectMessage) => {
      const { windowId, inputTargetId } = msg.payload as {
        windowId: AbjectId;
        inputTargetId?: AbjectId;
      };
      const targetId = (inputTargetId ?? msg.routing.from) as AbjectId;
      const widget = new CanvasWidget({
        type: 'canvas' as WidgetType,
        rect: { x: 0, y: 0, width: 0, height: 0 },
        ownerId: windowId,
        uiServerId: this.uiServerId!,
        theme: this.getThemeForWindow(windowId),
        inputTargetId: targetId,
      });
      const widgetId = await this.createTypedWidget(windowId, widget, { x: 0, y: 0, width: 0, height: 0 });

      // createTypedWidget skips adding 0x0 widgets to the window (they're
      // normally positioned by a layout). Canvas widgets always start at 0x0
      // and should fill the window content area when used without a layout.
      await this.request(
        request(this.id, windowId, 'addChild', {
          widgetId,
          rect: { x: 0, y: 0, width: 0, height: 0 },
        })
      );

      return widgetId;
    });

    // ── Shim methods (backward compat) ──

    this.on('addWidget', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: string;
        id: string;
        type: WidgetType;
        rect: { x: number; y: number; width: number; height: number };
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        placeholder?: string;
        monospace?: boolean;
        masked?: boolean;
      };
      return this.addWidget(msg.routing.from, payload);
    });

    this.on('updateWidget', async (msg: AbjectMessage) => {
      const { widgetId, ...updates } = msg.payload as {
        widgetId: string;
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        rect?: { x: number; y: number; width: number; height: number };
        masked?: boolean;
      };
      return this.updateWidget(widgetId, updates);
    });

    this.on('removeWidget', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.removeWidget(widgetId);
    });

    this.on('getWidgetValue', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.getWidgetValue(widgetId);
    });

    this.on('getDisplayInfo', async () => {
      require(this.uiServerId !== undefined, 'UIServer not set');
      return this.request<{ width: number; height: number }>(
        request(this.id, this.uiServerId!, 'getDisplayInfo', {})
      );
    });

    this.on('raiseWindow', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: AbjectId };
      if (!this.windowManagerId) return false;
      const surfaceId = this.windowSurfaces.get(windowId);
      if (!surfaceId) return false;
      return this.request(request(this.id, this.windowManagerId,
        'raiseWindow', { surfaceId }));
    });

    this.on('setObjectWorkspace', async (msg: AbjectMessage) => {
      const { objectId, workspaceId } = msg.payload as { objectId: AbjectId; workspaceId: string };
      this.objectWorkspaces.set(objectId, workspaceId);
      // Retroactively tag any existing windows owned by this object
      for (const [windowId, owner] of this.windowOwners.entries()) {
        if (owner === objectId) {
          const surfaceId = this.windowSurfaces.get(windowId);
          if (surfaceId) {
            await this.request(request(this.id, this.uiServerId!, 'setSurfaceWorkspace', { surfaceId, workspaceId }));
          }
        }
      }
    });

    this.on('registerWorkspaceTheme', async (msg: AbjectMessage) => {
      const { workspaceId, themeId } = msg.payload as { workspaceId: string; themeId: AbjectId };
      // Fetch current theme from the Theme object
      let theme: ThemeData = this.defaultTheme;
      try {
        const fetched = await this.request<ThemeData>(
          request(this.id, themeId, 'getTheme', {})
        );
        if (fetched && typeof fetched === 'object' && 'canvasBg' in fetched) {
          theme = fetched;
        }
      } catch { /* use default */ }

      // Subscribe for theme change notifications
      try {
        await this.request(
          request(this.id, themeId, 'addDependent', {})
        );
      } catch { /* may not support dependents */ }

      this.workspaceThemes.set(workspaceId, { themeId, theme });
      return true;
    });

    this.on('getObjectWorkspace', async (msg: AbjectMessage) => {
      const { objectId } = msg.payload as { objectId: string };
      return this.objectWorkspaces.get(objectId as AbjectId) ?? null;
    });

    // ── Modal confirmation dialog ──

    this.on('showConfirmDialog', (msg: AbjectMessage) => {
      const { title, message: dialogMessage, confirmLabel, cancelLabel, destructive } = msg.payload as {
        title: string;
        message: string;
        confirmLabel?: string;
        cancelLabel?: string;
        destructive?: boolean;
      };

      this.spawnModalDialog(title, dialogMessage, { confirmLabel, cancelLabel, destructive })
        .then(
          (confirmed) => this.sendDeferredReply(msg, confirmed),
          () => this.sendDeferredReply(msg, false),
        );

      return DEFERRED_REPLY;
    });

    this.on('objectUnregistered', async (msg: AbjectMessage) => {
      const objectId = msg.payload as AbjectId;
      await this.destroyWindowsForOwner(objectId);
    });

    // Handle 'changed' events from widget Abjects (dependency protocol)
    this.on('changed', async (msg: AbjectMessage) => {
      const { aspect, value } = msg.payload as { aspect: string; value?: unknown };
      const fromId = msg.routing.from;

      // Handle theme changes from per-workspace ThemeAbjects
      if (aspect === 'themeChanged') {
        // Find which workspace this theme belongs to
        let changedWorkspaceId: string | undefined;
        for (const [wsId, entry] of this.workspaceThemes) {
          if (entry.themeId === fromId) {
            entry.theme = value as ThemeData;
            changedWorkspaceId = wsId;
            break;
          }
        }
        if (changedWorkspaceId) {
          const newTheme = value as ThemeData;
          // Propagate only to widgets/windows in this workspace
          for (const id of this.spawnedWidgets) {
            if (this.getWorkspaceForWidgetOrWindow(id) === changedWorkspaceId) {
              try { this.send(event(this.id, id, 'updateTheme', newTheme)); } catch { /* gone */ }
            }
          }
          for (const id of this.spawnedWindows) {
            if (this.getWorkspaceForWidgetOrWindow(id) === changedWorkspaceId) {
              try { this.send(event(this.id, id, 'updateTheme', newTheme)); } catch { /* gone */ }
            }
          }
          return;
        }
      }

      // Forward window close/minimize/restore events to owners
      if (aspect === 'windowCloseRequested' || aspect === 'windowMinimized' || aspect === 'windowRestored') {
        const ownerId = this.windowOwners.get(fromId);
        if (ownerId) {
          this.send(event(this.id, ownerId,aspect, { windowId: fromId }));
        }
        return;
      }

      // Translate widget changed events to old-style widgetEvent messages
      const shimId = this.widgetIdToShimId.get(fromId);
      const windowShimId = this.widgetToWindowShimId.get(fromId);
      if (!shimId || !windowShimId) return;

      // Find the window's owner
      const windowAbjectId = this.shimWindowMap.get(windowShimId);
      if (!windowAbjectId) return;
      const ownerId = this.windowOwners.get(windowAbjectId);
      if (!ownerId) return;

      // Map aspect to old-style event type
      let eventType: 'click' | 'change' | 'submit' | undefined;
      if (aspect === 'click') eventType = 'click';
      else if (aspect === 'change') eventType = 'change';
      else if (aspect === 'submit') eventType = 'submit';

      if (eventType) {
        this.send(
          event(this.id, ownerId, 'widgetEvent', {
            windowId: windowShimId,
            widgetId: shimId,
            type: eventType,
            value: value !== undefined ? String(value) : undefined,
          })
        );
      }

      // Forward window events
      if (aspect === 'windowRect') {
        const { x, y, width, height } = value as { x: number; y: number; width: number; height: number };
        this.send(
          event(this.id, ownerId, 'windowMoved', { windowId: windowShimId, x, y })
        );
        this.send(
          event(this.id, ownerId, 'windowResized', { windowId: windowShimId, width, height })
        );
        // Keep WindowManager's tracked rect in sync (programmatic resize from owner)
        if (this.windowManagerId) {
          const surfaceId = this.windowSurfaces.get(fromId);
          if (surfaceId) {
            this.send(event(this.id, this.windowManagerId, 'updateWindowRect', {
              surfaceId, x, y, width, height,
            }));
          }
        }
      }
      if (aspect === 'windowMoved') {
        const { x, y } = value as { x: number; y: number };
        this.send(
          event(this.id, ownerId, 'windowMoved', { windowId: windowShimId, x, y })
        );
      }
      if (aspect === 'windowResized') {
        const { width, height } = value as { width: number; height: number };
        this.send(
          event(this.id, ownerId, 'windowResized', { windowId: windowShimId, width, height })
        );
      }
    });
  }

  protected override async onInit(): Promise<void> {
    this.uiServerId = await this.requireDep('UIServer');
    this.consoleId = await this.discoverDep('Console') ?? undefined;
    this.windowManagerId = await this.discoverDep('WindowManager') ?? undefined;

    // Subscribe to Registry for object-deletion cleanup
    const registryId = await this.discoverDep('Registry') ?? undefined;
    if (registryId) {
      try {
        await this.request(request(this.id, registryId,
          'subscribe', {}));
      } catch { /* best effort */ }
    }

    // Theme is per-workspace — registered via registerWorkspaceTheme from WorkspaceManager

    // Periodic sweep for orphaned windows whose owners are no longer on the bus.
    // The objectUnregistered event only covers the global registry; user apps in
    // workspace registries need this safety net.
    this.orphanSweepTimer = setInterval(() => {
      this.sweepOrphanedWindows();
    }, 5000);
  }

  protected override async onStop(): Promise<void> {
    if (this.orphanSweepTimer) {
      clearInterval(this.orphanSweepTimer);
      this.orphanSweepTimer = undefined;
    }
  }

  // ── Modal confirmation dialog — spawns an ephemeral ModalDialog Abject ──

  private async spawnModalDialog(
    title: string,
    dialogMessage: string,
    opts: { confirmLabel?: string; cancelLabel?: string; destructive?: boolean },
  ): Promise<boolean> {
    const dialog = new ModalDialog();
    dialog.setWidgetManagerId(this.id);
    await dialog.init(this.bus, this.id);
    return this.request<boolean>(
      request(this.id, dialog.id, 'show', {
        title,
        message: dialogMessage,
        ...opts,
        theme: this.defaultTheme,
      }),
      120000,
    );
  }

  /** Get theme for a window's owner (traces windowOwners → objectWorkspaces → workspace theme). */
  private getThemeForWindow(windowId: AbjectId): ThemeData {
    const ownerId = this.windowOwners.get(windowId);
    if (ownerId) return this.getThemeForOwner(ownerId);
    return this.defaultTheme;
  }

  /** Get theme for a given owner AbjectId (looks up owner's workspace → workspace theme → default). */
  private getThemeForOwner(ownerId: AbjectId): ThemeData {
    const wsId = this.objectWorkspaces.get(ownerId);
    if (wsId) {
      const entry = this.workspaceThemes.get(wsId);
      if (entry) return entry.theme;
    }
    return this.defaultTheme;
  }

  /** Get workspace ID for a widget/window by tracing through windowOwners → objectWorkspaces. */
  private getWorkspaceForWidgetOrWindow(id: AbjectId): string | undefined {
    // Direct: the id itself might be a window with an owner
    const ownerId = this.windowOwners.get(id);
    if (ownerId) {
      return this.objectWorkspaces.get(ownerId);
    }
    // Check if this is a widget → window → owner → workspace
    const windowId = this.widgetToWindow.get(id);
    if (windowId) {
      const winOwner = this.windowOwners.get(windowId);
      if (winOwner) return this.objectWorkspaces.get(winOwner);
    }
    // The id might be in objectWorkspaces directly (unlikely for widgets, but check)
    return this.objectWorkspaces.get(id);
  }

  private async log(level: string, message: string, data?: unknown): Promise<void> {
    if (!this.consoleId) return;
    try {
      this.send(
        request(this.id, this.consoleId, level, { message, data })
      );
    } catch { /* logging should never break the caller */ }
  }

  protected override getSourceForAsk(): string | undefined {
    return `## WidgetManager Usage Guide

### Complete Workflow Example

// 1. Create a window
const winId = await this.call(this.dep('WidgetManager'), 'createWindowAbject', {
  title: 'My Window', rect: { x: 100, y: 100, width: 400, height: 300 }, resizable: true
});

// 2. Create a vertical layout
const layoutId = await this.call(this.dep('WidgetManager'), 'createVBox', {
  windowId: winId, margins: { top: 8, right: 16, bottom: 8, left: 16 }, spacing: 8
});

// 3. Batch-create widgets (returns { widgetIds } in same order as specs)
const { widgetIds } = await this.call(this.dep('WidgetManager'), 'create', {
  specs: [
    { type: 'label', windowId: winId, text: 'Hello World' },
    { type: 'button', windowId: winId, text: 'Click Me' },
    { type: 'textInput', windowId: winId, placeholder: 'Type here...' },
  ]
});
const [labelId, btnId, inputId] = widgetIds;

// 4. Add widgets to layout (layout manages positioning)
await this.call(layoutId, 'addLayoutChildren', {
  children: [
    { widgetId: labelId, sizePolicy: { vertical: 'fixed' }, preferredSize: { height: 20 } },
    { widgetId: inputId, sizePolicy: { vertical: 'fixed', horizontal: 'expanding' }, preferredSize: { height: 36 } },
    { widgetId: btnId, sizePolicy: { horizontal: 'fixed' }, preferredSize: { width: 100, height: 36 } },
  ]
});

// Add a spacer to push widgets apart:
await this.call(layoutId, 'addLayoutSpacer', {});

// 5. Register for button click events
await this.call(btnId, 'addDependent', {});

// 6. Handle events — implement a 'changed' handler in your handler map:
async changed(msg) {
  const { aspect, value } = msg.payload;
  const fromId = msg.routing.from;
  if (fromId === this._btnId && aspect === 'click') {
    // Button was clicked
  }
  if (fromId === this._inputId && aspect === 'submit') {
    // Enter pressed in text input
  }
}

### Updating Widgets

// Update label text:
await this.call(labelId, 'update', { text: 'New text' });

// Get text input value:
const value = await this.call(inputId, 'getValue', {});

### Destroying a Window

await this.call(this.dep('WidgetManager'), 'destroyWindowAbject', { windowId: winId });

### Widget Types (used as \`type\` in create() specs)

label - Static text display. Style: { wordWrap: true } for multi-line text. Style: { selectable: true } to allow users to click-drag, double-click, Shift+click, Ctrl+A, and Ctrl+C to select and copy text (read-only).
button - Clickable button (listen for 'changed' with aspect 'click'). Keyboard: Enter/Space when focused.
textInput - Single-line text input (aspects: 'change', 'submit')
textArea - Multi-line text area (params: monospace?)
checkbox - Toggle checkbox (aspect: 'change', value: boolean). Keyboard: Space when focused.
progress - Progress bar (update with { value: 0-100 })
divider - Horizontal divider line
select - Dropdown select (params: options[], selectedIndex). Keyboard: Enter/Space to open, ArrowUp/Down to navigate, Enter to select, Escape to close.
tabBar - Tab bar (params: tabs[] of labels, selectedIndex). Fires 'change' event with selected index. Keyboard: ArrowLeft/Right to switch tabs.
slider - Numeric range slider (params: min, max, step, value). Fires 'change' event with numeric value as string. Keyboard: ArrowLeft/Right ±step, Home/End for min/max. Click track or drag thumb.
image - Image display (params: url, fit 'contain'|'cover'|'fill', alt). Non-interactive. Update URL via this.call(imgId, 'update', { url: '...' }).
list - Scrollable list (params: items[], selectedIndex?, searchable?, itemHeight?). Fires 'selectionChanged'.
splitPane - Resizable split view (params: orientation?, dividerPosition?, minSize?).

### Widget Style Properties

All widgets accept a \`style\` object with these optional properties:
- color, background, borderColor — colors
- fontSize, fontWeight ('normal' | 'bold'), align ('left' | 'center' | 'right') — typography
- radius — border radius
- wordWrap — enable word wrapping on labels
- selectable — labels only: enable read-only text selection (click-drag, double-click word select, Shift+click, Ctrl+A, Ctrl+C)
- disabled — when true, widget renders at 50% opacity and ignores all input (except textInput/textArea which still allow text selection and copy)
- visible — when false, widget renders nothing and ignores input (default: true)

### Disabling Widgets During Async Operations

// Disable a button while an operation is in progress:
await this.call(btnId, 'update', { style: { disabled: true } });

// ... perform async operation ...

// Re-enable when done:
await this.call(btnId, 'update', { style: { disabled: false } });

### Keyboard Shortcuts (Focus Required)

- Button: Enter or Space → fires 'click'
- Checkbox: Space → toggles checked state
- Select: Enter/Space → opens dropdown; ArrowUp/Down → navigate options; Enter → select; Escape → close
- TextInput: Backspace/Delete (delete chars), ArrowLeft/Right (move cursor), Home/End (jump to start/end),
  Ctrl+A (select all), Ctrl+C/X (copy/cut), Enter (fires 'submit' aspect), Tab (bubbles — advances focus),
  Shift+Arrow (extends selection), click-drag (select range), double-click (select word), Shift+click (extend selection),
  printable characters insert text at cursor. When disabled: selection, copy, and navigation still work; editing is blocked.
- TextArea: All TextInput keys plus ArrowUp/Down (line navigation), Tab (inserts 2-space indent, consumed),
  mouse wheel (scrolls content), click-drag (select range), double-click (select word), Shift+click (extend selection).
  Enter inserts a newline (does NOT submit). When disabled: selection, copy, and navigation still work; editing is blocked.
- TabBar: ArrowLeft/Right → switch tabs
- Slider: ArrowLeft/Right/Up/Down → ±step; Home → min; End → max
- Selectable Label: Ctrl+A (select all), Ctrl+C (copy), Shift+Arrow (extend selection), Home/End (jump), double-click (select word), click-drag (select range)

### Layout Types

createVBox - Vertical stack layout
createHBox - Horizontal row layout
createNestedVBox - Nested vertical layout inside another layout. Pass autoSize: true for auto-computed preferred height (use inside ScrollableVBox for card items).
createNestedHBox - Nested horizontal layout inside another layout. Pass autoSize: true for auto-computed preferred height.
createScrollableVBox - Scrollable vertical stack layout (clips overflow, scrolls via mouse wheel). Pass autoScroll: true to pin to bottom when content is added (for chat/log views).
createNestedScrollableVBox - Nested scrollable vertical layout inside another layout. Pass autoScroll: true to pin to bottom when content is added (for chat/log views).

### Canvas Drawing (games, animations, visualizations)

createCanvas - Drawing area inside a window. Returns canvasId (AbjectId).

const canvasId = await this.call(this.dep('WidgetManager'), 'createCanvas', {
  windowId: winId
});

// When combining canvas with a layout (e.g. toolbar + canvas):
// add the canvas to the layout so it shares space with other widgets.
await this.call(rootLayout, 'addLayoutChildren', {
  children: [{
    widgetId: canvasId,
    sizePolicy: { horizontal: 'expanding', vertical: 'expanding' }
  }]
});

// Get canvas dimensions (set by layout or window content area):
const { width, height } = await this.call(canvasId, 'getCanvasSize', {});

// Available draw command types:
// Shapes: clear, rect, text, line, path, circle, arc, ellipse, polygon, bezierCurve, quadraticCurve, imageUrl
// State: save, restore, clip
// Transforms: translate, rotate, scale
// Effects: globalAlpha, shadow, setLineDash, linearGradient, radialGradient
// Text supports maxWidth: { type: 'text', params: { ..., maxWidth: 200 } } — auto-shrinks text to fit

// Draw using standard draw commands (coordinates are canvas-local, starting at 0,0):
await this.call(canvasId, 'draw', {
  commands: [
    { type: 'clear', surfaceId: 'c', params: { color: '#1a1a2e' } },
    { type: 'rect', surfaceId: 'c', params: { x: 10, y: 10, width: 50, height: 50, fill: '#ff0' } },
    { type: 'circle', surfaceId: 'c', params: { cx: 100, cy: 100, radius: 30, fill: '#39ff8e' } },
  ]
});

// Displaying images (fetch as base64, then draw with imageUrl):
const img = await this.call(this.dep('HttpClient'), 'getBase64', { url: 'https://example.com/photo.jpg' });
await this.call(canvasId, 'draw', {
  commands: [{ type: 'imageUrl', surfaceId: 'c', params: { x: 0, y: 0, width: 200, height: 150, url: img.dataUri } }]
});

// Input events: click the canvas to focus it, then keydown/keyup arrive via your 'input' handler.
// Mouse events (mousedown, mouseup, mousemove, wheel) also arrive with canvas-local x, y coordinates.
// A synthetic 'canvasResize' event fires when the canvas is resized by the layout system.

// Event payload shape:
// { type, key, code, modifiers: { shift, ctrl, alt, meta }, x, y, button, deltaX, deltaY }
//
// key vs code:
//   key  = logical key produced: 'a', 'A', 'Enter', 'ArrowUp', ' ' (space)
//   code = physical key location: 'KeyA', 'Enter', 'ArrowUp', 'Space'
//   Use 'key' for character input, 'code' for game controls (WASD always same physical keys).
//
// Modifier keys: check modifiers.shift, modifiers.ctrl, modifiers.alt, modifiers.meta

// Example: canvas keyboard handler for a game/app
async input(msg) {
  const { type, key, code, modifiers, x, y } = msg.payload;
  if (type === 'keydown') {
    if (code === 'ArrowUp' || code === 'KeyW') { /* move up */ }
    if (code === 'ArrowDown' || code === 'KeyS') { /* move down */ }
    if (key === 'Enter') { /* confirm action */ }
    if (modifiers.ctrl && key === 'z') { /* undo */ }
  }
  if (type === 'mousedown') { /* click at canvas-local (x, y) */ }
  if (type === 'canvasResize') {
    const { width, height } = msg.payload;
    // Adjust layout for new canvas dimensions
  }
}

### Updating Layout Children

// Change a child's size policy or preferred size after initial layout:
await this.call(layoutId, 'updateLayoutChild', {
  widgetId: childId, sizePolicy: { vertical: 'expanding' }, preferredSize: { height: 200 }
});

### Utility Methods

getDisplayInfo - Returns { width, height } of the display area

### Window Close, Minimize, and Restore Events

Windows with title bars have close (X) and minimize (_) buttons. WidgetManager forwards
these events to the window's owner as method calls on 'abjects:widgets':

- 'windowCloseRequested' — close button clicked. Payload: { windowId }. Owner should call hide() or destroyWindowAbject.
- 'windowMinimized' — window was minimized to taskbar. Payload: { windowId }. Informational only.
- 'windowRestored' — window was restored from taskbar. Payload: { windowId }. Informational only.

Handle them in your setupHandlers():
  this.on('windowCloseRequested', async (msg) => {
    const { windowId } = msg.payload;
    await this.hide();
  });

### Common Layout Patterns

// Note: Nested layouts (createNestedVBox, createNestedHBox, createNestedScrollableVBox)
// are auto-added to their parent with expanding policy. Use addLayoutChild only to
// override sizing (e.g. fixed height or custom stretch).

// Header + scrollable content + footer (VBox with fixed/expanding/fixed):
const rootLayout = await this.call(this.dep('WidgetManager'), 'createVBox', {
  windowId: winId, margins: { top: 8, right: 16, bottom: 8, left: 16 }, spacing: 8
});
const { widgetIds: [header] } = await this.call(this.dep('WidgetManager'), 'create', {
  specs: [{ type: 'label', windowId: winId, text: 'Title', style: { fontSize: 18, fontWeight: 'bold' } }]
});
await this.call(rootLayout, 'addLayoutChild', {
  widgetId: header, sizePolicy: { vertical: 'fixed' }, preferredSize: { height: 28 }
});
// Scrollable content area (auto-added to parent with expanding policy)
const scrollArea = await this.call(this.dep('WidgetManager'), 'createNestedScrollableVBox', {
  parentLayoutId: rootLayout, spacing: 4
});

// Side-by-side panels (HBox with fixed sidebar + expanding main area):
const hbox = await this.call(this.dep('WidgetManager'), 'createHBox', {
  windowId: winId, spacing: 8
});
const sidebar = await this.call(this.dep('WidgetManager'), 'createNestedVBox', {
  parentLayoutId: hbox, spacing: 4
});
// Make sidebar fixed-width (default is expanding which splits 50/50)
await this.call(hbox, 'updateLayoutChild', {
  widgetId: sidebar,
  sizePolicy: { horizontal: 'fixed' },
  preferredSize: { width: 200 }
});
const mainArea = await this.call(this.dep('WidgetManager'), 'createNestedVBox', {
  parentLayoutId: hbox, spacing: 4
});
// mainArea stays expanding (default) and fills remaining width

### Tab Content Switching

// Create a TabBar + multiple content layouts, show/hide based on tab selection:
const { widgetIds: [tabBar] } = await this.call(this.dep('WidgetManager'), 'create', {
  specs: [{ type: 'tabBar', windowId: winId, tabs: ['Tab A', 'Tab B', 'Tab C'] }]
});
await this.call(rootLayout, 'addLayoutChild', {
  widgetId: tabBar, sizePolicy: { vertical: 'fixed' }, preferredSize: { height: 36 }
});
await this.call(tabBar, 'addDependent', {});

// Create one content layout per tab (auto-added to parent with expanding policy)
const tabContents = [];
for (const tabName of ['Tab A', 'Tab B', 'Tab C']) {
  const content = await this.call(this.dep('WidgetManager'), 'createNestedVBox', {
    parentLayoutId: rootLayout, spacing: 4
  });
  tabContents.push(content);
}

// Initially hide all but first tab
for (let i = 1; i < tabContents.length; i++) {
  await this.call(tabContents[i], 'update', { style: { visible: false } });
}

// In your 'changed' handler, toggle visibility:
// if (fromId === tabBar && aspect === 'change') {
//   for (let i = 0; i < tabContents.length; i++) {
//     await this.call(tabContents[i], 'update', { style: { visible: i === parseInt(value) } });
//   }
// }

### Dynamic Widget Management

// Add a widget to a layout at runtime:
await this.call(layoutId, 'addLayoutChild', {
  widgetId: newWidgetId, sizePolicy: { vertical: 'fixed' }, preferredSize: { height: 36 }
});

// Remove a widget from its layout (via WidgetManager):
await this.call(this.dep('WidgetManager'), 'removeWidget', { widgetId: widgetId });

// Remove a widget from a specific layout:
await this.call(layoutId, 'removeLayoutChild', { widgetId: widgetId });

// Destroy a widget (stop its Abject and free resources):
await this.call(widgetId, 'destroy', {});

// Bring a window to the front:
await this.call(this.dep('WidgetManager'), 'raiseWindow', { windowId: winId });

### Animation Pattern

// Use Timer to drive a canvas animation loop:
const timerId = this.dep('Timer');
const intervalId = await this.call(timerId, 'setInterval', { ms: 16 }); // ~60fps
await this.call(timerId, 'addDependent', {});

// In your 'changed' handler:
// if (fromId === timerId && aspect === 'tick') {
//   this.updateState();
//   await this._draw(); // redraw canvas
// }

// Stop animation:
// await this.call(timerId, 'clearInterval', { intervalId });

### UI Design Best Practices

**Window Sizing** — Match window size to content complexity:
- Simple dialogs/forms: 350×250
- Content apps (readers, lists): 500×450 or larger
- Dashboards/multi-panel: 600×500 or larger

**Typography Hierarchy** — Create visual hierarchy with font size and weight:
- Headings: 16–18px, bold
- Body text: 14px, normal weight
- Metadata/secondary info: 12px, color '#8a8a9e'
- Use bold sparingly for emphasis within body text

**Spacing** — Consistent spacing creates a polished look:
- Root container margins: 16px on all sides
- Standard spacing between elements: 8px
- Tight spacing (related items): 4px
- Loose spacing (section breaks): 12px

**Content Lists / Card Patterns** — For apps that display collections of items:
- Use a ScrollableVBox (grow: 1) as the main content area
- Each item is a VBox with: bold 15px title, 12px secondary-color date, 13px word-wrapped summary
- Add a Divider between items for visual separation
- Add a header row (HBox) with a bold title and a right-aligned status label in secondary color

**Word-Wrapped Labels** — Labels with wordWrap: true need height estimates:
- Use sizePolicy: { vertical: 'fixed' } and estimate height (~18px per line at fontSize 14)
- Rough formula: lines = ceil(textLength * fontSize * 0.55 / containerWidth), height = lines * (fontSize + 4)
- When in doubt, over-estimate slightly — extra whitespace is better than clipped text

**Nested Layouts in ScrollableVBox** — Use autoSize: true for nested layouts inside a ScrollableVBox:
- Pass autoSize: true when creating nested VBox/HBox inside a ScrollableVBox (e.g. card items)
- The nested layout auto-computes its preferred height from children and reports it to the parent
- Just ensure inner widgets have proper preferredSize set (especially height for labels)
- Do NOT use autoSize for layouts that should fill available space (expanding policy)

**Flat vs Nested Layouts** — Choose the simplest structure:
- For simple card lists, prefer flat layout: all widgets directly in the scroll box with dividers
- Use nested VBox only when you need a group of related items with different spacing/margins
- Deeply nested structures add overhead — keep nesting to 2 levels max when possible

`;
  }

  /**
   * Destroy all windows owned by a specific object.
   */
  private async sweepOrphanedWindows(): Promise<void> {
    const deadOwners = new Set<AbjectId>();
    for (const [_windowId, ownerId] of this.windowOwners) {
      if (!this.bus.isRegistered(ownerId)) {
        deadOwners.add(ownerId);
      }
    }
    for (const ownerId of deadOwners) {
      await this.destroyWindowsForOwner(ownerId);
    }
  }

  private async destroyWindowsForOwner(ownerId: AbjectId): Promise<number> {
    const windowIds: AbjectId[] = [];
    for (const [windowId, owner] of this.windowOwners.entries()) {
      if (owner === ownerId) windowIds.push(windowId);
    }
    let count = 0;
    for (const windowId of windowIds) {
      if (await this.destroyWindowDirect(windowId)) count++;
    }
    return count;
  }

  // ── Factory: createWindow ─────────────────────────────────────────────

  private async createWindow(
    owner: AbjectId,
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; resizable?: boolean; zIndex?: number }
  ): Promise<string> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const ownerTheme = this.getThemeForOwner(owner);
    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      resizable: options?.resizable,
      zIndex: options?.zIndex ?? 100,
      theme: ownerTheme,
    });

    await win.init(this.bus, this.id);
    this.spawnedWindows.add(win.id);

    // Tag the surface with the owner's workspace (if known)
    const ownerWs = this.objectWorkspaces.get(owner);
    if (ownerWs && win.surface) {
      await this.request(request(this.id, this.uiServerId!, 'setSurfaceWorkspace', { surfaceId: win.surface, workspaceId: ownerWs }));
    }

    // Register as dependent of the window (for windowMoved/windowResized events)
    await this.request(
      request(this.id, win.id, 'addDependent', {})
    );

    // Register with WindowManager for z-order and drag/resize management
    if (this.windowManagerId && win.surface) {
      try {
        await this.request(request(this.id, this.windowManagerId,
          'registerWindow', {
            surfaceId: win.surface, windowId: win.id, zIndex: options?.zIndex ?? 100,
            rect, chromeless: options?.chromeless ?? false,
            draggable: false,
            title,
            titleBarHeight: ownerTheme.titleBarHeight,
            titleButtonSize: ownerTheme.titleButtonSize,
            titleButtonMargin: ownerTheme.titleButtonMargin,
            workspaceId: ownerWs,
          }));
      } catch { /* WindowManager may not be ready */ }
    }

    // Generate a shim window ID for backward compat
    const shimWindowId = `wm-win-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    this.shimWindowMap.set(shimWindowId, win.id);
    this.windowOwners.set(win.id, owner);

    return shimWindowId;
  }

  // ── Factory: createWindowDirect — returns AbjectId ──────────────────

  private async createWindowDirect(
    owner: AbjectId,
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; transparent?: boolean; resizable?: boolean; draggable?: boolean; zIndex?: number }
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const ownerTheme = this.getThemeForOwner(owner);
    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      transparent: options?.transparent,
      resizable: options?.resizable,
      draggable: options?.draggable,
      zIndex: options?.zIndex ?? 100,
      theme: ownerTheme,
    });

    await win.init(this.bus, this.id);
    this.spawnedWindows.add(win.id);
    this.windowOwners.set(win.id, owner);
    if (win.surface) this.windowSurfaces.set(win.id, win.surface);
    this.log('debug', 'createWindowAbject', { windowId: win.id, title });

    // Tag the surface with the owner's workspace (if known)
    const ownerWs = this.objectWorkspaces.get(owner);
    if (ownerWs && win.surface) {
      await this.request(request(this.id, this.uiServerId!, 'setSurfaceWorkspace', { surfaceId: win.surface, workspaceId: ownerWs }));
    }

    // Register as dependent of the window (for window events)
    await this.request(
      request(this.id, win.id, 'addDependent', {})
    );

    // Register with WindowManager for z-order and drag/resize management
    if (this.windowManagerId && win.surface) {
      try {
        await this.request(request(this.id, this.windowManagerId,
          'registerWindow', {
            surfaceId: win.surface, windowId: win.id, zIndex: options?.zIndex ?? 100,
            rect, chromeless: options?.chromeless ?? false,
            draggable: options?.draggable ?? false,
            title,
            titleBarHeight: ownerTheme.titleBarHeight,
            titleButtonSize: ownerTheme.titleButtonSize,
            titleButtonMargin: ownerTheme.titleButtonMargin,
            workspaceId: ownerWs,
          }));
        log.info(`registerWindow surface=${win.surface} wmId=${this.windowManagerId}`);
        // Bring newly created window to front so it isn't hidden behind existing windows
        await this.request(request(this.id, this.windowManagerId,
          'raiseWindow', { surfaceId: win.surface }));
      } catch { /* WindowManager may not be ready */ }
    }

    return win.id;
  }

  // ── Factory: destroyWindowDirect — destroy by AbjectId ─────────────

  private async destroyWindowDirect(windowId: AbjectId): Promise<boolean> {
    if (!this.spawnedWindows.has(windowId)) return false;
    console.debug(`[WidgetManager] destroyWindowDirect(${windowId})`);

    // Unregister from WindowManager
    if (this.windowManagerId) {
      try {
        this.send(event(this.id, this.windowManagerId,
          'unregisterWindow', { windowId }));
      } catch { /* WM may be gone */ }
    }

    try {
      console.debug(`[WidgetManager] sending destroy request to WindowAbject ${windowId}`);
      await this.request(
        request(this.id, windowId, 'destroy', {})
      );
      console.debug(`[WidgetManager] WindowAbject ${windowId} destroyed`);
    } catch {
      // Window may already be stopped
    }

    this.spawnedWindows.delete(windowId);
    this.windowSurfaces.delete(windowId);

    // Clean up child widget shim entries for this window
    // Reverse-lookup shimWindowMap to find the window's shim ID
    let windowShimId: string | undefined;
    for (const [shimId, abjectId] of this.shimWindowMap.entries()) {
      if (abjectId === windowId) {
        windowShimId = shimId;
        this.shimWindowMap.delete(shimId);
        break;
      }
    }
    this.windowOwners.delete(windowId);

    // Clean up widgetToWindow entries for this window's children
    for (const [widgetId, winId] of this.widgetToWindow.entries()) {
      if (winId === windowId) {
        this.widgetToWindow.delete(widgetId);
      }
    }

    if (windowShimId) {
      for (const [shimId, abjectId] of this.shimWidgetMap.entries()) {
        if (this.widgetToWindowShimId.get(abjectId) === windowShimId) {
          this.shimWidgetMap.delete(shimId);
          this.widgetIdToShimId.delete(abjectId);
          this.widgetToWindowShimId.delete(abjectId);
          this.spawnedWidgets.delete(abjectId);
        }
      }
    }

    return true;
  }

  // ── Factory: createLayoutWidget — init layout and add as window child ──

  private async createLayoutWidget(
    windowId: AbjectId,
    layout: LayoutAbject
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await layout.init(this.bus, this.id);
    this.spawnedWidgets.add(layout.id);

    // Add the layout as the window's child with a full-content rect
    // The window will update this rect on resize
    await this.request(
      request(this.id, windowId, 'addChild', {
        widgetId: layout.id,
        rect: { x: 0, y: 0, width: 0, height: 0 },
      })
    );

    return layout.id;
  }

  // ── Factory: createNestedLayout — init layout and add to parent layout ──

  private async createNestedLayout(
    parentLayoutId: AbjectId,
    layout: LayoutAbject,
    autoSize?: boolean,
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    // When autoSize is enabled, the nested layout will auto-compute its
    // preferred height from children and report it to the parent. This
    // switches the child's sizePolicy to 'preferred' so the parent
    // allocates the exact height needed (essential inside ScrollableVBox).
    if (autoSize) {
      layout.setParentLayoutId(parentLayoutId);
    }

    await layout.init(this.bus, this.id);
    this.spawnedWidgets.add(layout.id);

    // Auto-add to parent with expanding defaults
    await this.request(request(this.id, parentLayoutId, 'addLayoutChild', {
      widgetId: layout.id,
      sizePolicy: { vertical: 'expanding', horizontal: 'expanding' },
    }));

    return layout.id;
  }

  // ── Factory: createTypedWidget (shared helper for factory methods) ───

  private async createWidgetFromSpec(spec: {
    type: string;
    windowId: AbjectId;
    rect?: Rect;
    text?: string;
    style?: WidgetStyle;
    placeholder?: string;
    masked?: boolean;
    wordWrap?: boolean;
    minLines?: number;
    maxLines?: number;
    monospace?: boolean;
    checked?: boolean;
    value?: number;
    options?: string[];
    selectedIndex?: number;
    tabs?: string[];
    min?: number;
    max?: number;
    step?: number;
    url?: string;
    fit?: 'contain' | 'cover' | 'fill';
    alt?: string;
    items?: ListItem[];
    searchable?: boolean;
    itemHeight?: number;
  }): Promise<AbjectId> {
    const rect = spec.rect ?? { x: 0, y: 0, width: 0, height: 0 };
    const theme = this.getThemeForWindow(spec.windowId);
    const base = { ownerId: spec.windowId, uiServerId: this.uiServerId!, theme };

    switch (spec.type) {
      case 'label':
        return this.createTypedWidget(spec.windowId, new LabelWidget({
          type: 'label', rect, text: spec.text, style: spec.style, ...base,
        }), rect);
      case 'button':
        return this.createTypedWidget(spec.windowId, new ButtonWidget({
          type: 'button', rect, text: spec.text, style: spec.style, ...base,
        }), rect);
      case 'textInput':
        return this.createTypedWidget(spec.windowId, new TextInputWidget({
          type: 'textInput', rect, text: spec.text, style: spec.style,
          placeholder: spec.placeholder, masked: spec.masked,
          wordWrap: spec.wordWrap, minLines: spec.minLines, maxLines: spec.maxLines,
          ...base,
        }), rect);
      case 'textArea':
        return this.createTypedWidget(spec.windowId, new TextAreaWidget({
          type: 'textArea', rect, text: spec.text, style: spec.style,
          monospace: spec.monospace, ...base,
        }), rect);
      case 'checkbox':
        return this.createTypedWidget(spec.windowId, new CheckboxWidget({
          type: 'checkbox', rect, text: spec.text, style: spec.style,
          checked: spec.checked, ...base,
        }), rect);
      case 'progress':
        return this.createTypedWidget(spec.windowId, new ProgressWidget({
          type: 'progress', rect, text: spec.text, style: spec.style,
          value: spec.value, ...base,
        }), rect);
      case 'divider':
        return this.createTypedWidget(spec.windowId, new DividerWidget({
          type: 'divider', rect, style: spec.style, ...base,
        }), rect);
      case 'select':
        return this.createTypedWidget(spec.windowId, new SelectWidget({
          type: 'select', rect, text: spec.text, style: spec.style,
          options: spec.options, selectedIndex: spec.selectedIndex, ...base,
        }), rect);
      case 'tabBar':
        return this.createTypedWidget(spec.windowId, new TabBarWidget({
          type: 'tabBar', rect, style: spec.style,
          tabs: spec.tabs, selectedIndex: spec.selectedIndex, ...base,
        }), rect);
      case 'slider':
        return this.createTypedWidget(spec.windowId, new SliderWidget({
          type: 'slider', rect, text: spec.text, style: spec.style,
          min: spec.min, max: spec.max, step: spec.step, value: spec.value, ...base,
        }), rect);
      case 'image':
        return this.createTypedWidget(spec.windowId, new ImageWidget({
          type: 'image', rect, style: spec.style,
          url: spec.url, fit: spec.fit, alt: spec.alt, ...base,
        }), rect);
      case 'list':
        return this.createTypedWidget(spec.windowId, new ListWidget({
          type: 'label' as WidgetType, rect, style: spec.style,
          items: spec.items, selectedIndex: spec.selectedIndex,
          searchable: spec.searchable, itemHeight: spec.itemHeight, ...base,
        }), rect);
      default:
        throw new Error(`Unknown widget type in create: ${spec.type}`);
    }
  }

  private async createTypedWidget(
    windowId: AbjectId,
    widget: WidgetAbject,
    rect: Rect
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await widget.init(this.bus, this.id);
    this.spawnedWidgets.add(widget.id);
    this.widgetToWindow.set(widget.id, windowId);
    this.log('debug', 'createWidget', { widgetId: widget.id, windowId, type: widget.manifest.name });

    // Only add to window if rect is non-zero.
    // Layout-managed widgets pass {0,0,0,0} and are positioned by their layout.
    if (rect.width > 0 || rect.height > 0) {
      await this.request(
        request(this.id, windowId, 'addChild', {
          widgetId: widget.id,
          rect,
        })
      );
    }

    return widget.id;
  }

  // ── Factory: destroyWindow ────────────────────────────────────────────

  private async destroyWindow(owner: AbjectId, windowId: string): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(windowId);
    if (!winAbjectId) return false;

    // Verify ownership
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    // Unregister from WindowManager
    if (this.windowManagerId) {
      try {
        this.send(event(this.id, this.windowManagerId,
          'unregisterWindow', { windowId: winAbjectId }));
      } catch { /* WM may be gone */ }
    }

    // Send destroy message to WindowAbject (it will destroy all children)
    try {
      await this.request(
        request(this.id, winAbjectId, 'destroy', {})
      );
    } catch {
      // Window may already be stopped
    }

    // Clean up shim maps
    this.shimWindowMap.delete(windowId);
    this.windowOwners.delete(winAbjectId);
    this.spawnedWindows.delete(winAbjectId);

    // Clean up widget shim entries for this window
    for (const [shimId, abjectId] of this.shimWidgetMap.entries()) {
      if (this.widgetToWindowShimId.get(abjectId) === windowId) {
        this.shimWidgetMap.delete(shimId);
        this.widgetIdToShimId.delete(abjectId);
        this.widgetToWindowShimId.delete(abjectId);
        this.spawnedWidgets.delete(abjectId);
      }
    }

    return true;
  }

  // ── Shim: addWidget ───────────────────────────────────────────────────

  private async addWidget(
    owner: AbjectId,
    config: {
      windowId: string;
      id: string;
      type: WidgetType;
      rect: { x: number; y: number; width: number; height: number };
      text?: string;
      style?: WidgetStyle;
      checked?: boolean;
      value?: number;
      options?: string[];
      selectedIndex?: number;
      placeholder?: string;
      monospace?: boolean;
      masked?: boolean;
      tabs?: string[];
      min?: number;
      max?: number;
      step?: number;
      url?: string;
      fit?: 'contain' | 'cover' | 'fill';
      alt?: string;
    }
  ): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(config.windowId);
    if (!winAbjectId) return false;
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    require(this.uiServerId !== undefined, 'UIServer not set');

    // Create the appropriate widget Abject
    const baseConfig: WidgetConfig = {
      type: config.type,
      rect: config.rect,
      text: config.text,
      style: config.style,
      ownerId: winAbjectId,
      uiServerId: this.uiServerId!,
      theme: this.getThemeForWindow(winAbjectId),
    };

    let widget: WidgetAbject;

    switch (config.type) {
      case 'label':
        widget = new LabelWidget(baseConfig);
        break;
      case 'button':
        widget = new ButtonWidget(baseConfig);
        break;
      case 'textInput':
        widget = new TextInputWidget({
          ...baseConfig,
          placeholder: config.placeholder,
          masked: config.masked,
        } as TextInputWidgetConfig);
        break;
      case 'textArea':
        widget = new TextAreaWidget({
          ...baseConfig,
          monospace: config.monospace,
        } as TextAreaWidgetConfig);
        break;
      case 'checkbox':
        widget = new CheckboxWidget({
          ...baseConfig,
          checked: config.checked,
        } as CheckboxWidgetConfig);
        break;
      case 'progress':
        widget = new ProgressWidget({
          ...baseConfig,
          value: config.value,
        } as ProgressWidgetConfig);
        break;
      case 'divider':
        widget = new DividerWidget(baseConfig);
        break;
      case 'select':
        widget = new SelectWidget({
          ...baseConfig,
          options: config.options,
          selectedIndex: config.selectedIndex,
        } as SelectWidgetConfig);
        break;
      case 'tabBar':
        widget = new TabBarWidget({
          ...baseConfig,
          tabs: config.tabs,
          selectedIndex: config.selectedIndex,
        } as TabBarConfig);
        break;
      case 'slider':
        widget = new SliderWidget({
          ...baseConfig,
          min: config.min,
          max: config.max,
          step: config.step,
          value: config.value,
        } as SliderWidgetConfig);
        break;
      case 'image':
        widget = new ImageWidget({
          ...baseConfig,
          url: config.url,
          fit: config.fit,
          alt: config.alt,
        } as ImageWidgetConfig);
        break;
      default:
        return false;
    }

    await widget.init(this.bus, this.id);
    this.spawnedWidgets.add(widget.id);

    // Register WidgetManager as dependent of the widget (for event translation)
    await this.request(
      request(this.id, widget.id, 'addDependent', {})
    );

    // Track shim mappings
    this.shimWidgetMap.set(config.id, widget.id);
    this.widgetIdToShimId.set(widget.id, config.id);
    this.widgetToWindowShimId.set(widget.id, config.windowId);

    // Tell the WindowAbject to add this child
    await this.request(
      request(this.id, winAbjectId, 'addChild', {
        widgetId: widget.id,
        rect: config.rect,
      })
    );

    return true;
  }

  // ── Shim: updateWidget ────────────────────────────────────────────────

  private async updateWidget(
    widgetId: string,
    updates: Record<string, unknown>
  ): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    try {
      await this.request(
        request(this.id, abjectId, 'update', updates)
      );
      return true;
    } catch {
      return false;
    }
  }

  // ── Shim: removeWidget ────────────────────────────────────────────────

  private async removeWidget(widgetId: string): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    const windowShimId = this.widgetToWindowShimId.get(abjectId);
    if (windowShimId) {
      const winAbjectId = this.shimWindowMap.get(windowShimId);
      if (winAbjectId) {
        try {
          await this.request(
            request(this.id, winAbjectId, 'removeChild', { widgetId: abjectId })
          );
        } catch {
          // Window may be gone
        }
      }
    }

    // Destroy the widget (must use request() so the reply is consumed)
    try {
      await this.request(request(this.id, abjectId, 'destroy', {}));
    } catch {
      // Widget may be gone
    }

    this.shimWidgetMap.delete(widgetId);
    this.widgetIdToShimId.delete(abjectId);
    this.widgetToWindowShimId.delete(abjectId);
    this.spawnedWidgets.delete(abjectId);

    return true;
  }

  // ── Shim: getWidgetValue ──────────────────────────────────────────────

  private async getWidgetValue(widgetId: string): Promise<string> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return '';

    try {
      return await this.request<string>(
        request(this.id, abjectId, 'getValue', {})
      );
    } catch {
      return '';
    }
  }
}

// Well-known WidgetManager ID
export const WIDGET_MANAGER_ID = 'abjects:widget-manager' as AbjectId;
