/**
 * Widget Manager — factory that spawns WindowAbject and WidgetAbject instances.
 *
 * WidgetManager is a thin factory. It spawns widget Abjects on the bus and
 * returns their AbjectIds. All rendering, input handling, and state management
 * lives in the widget Abjects themselves.
 *
 * Primary API (returns AbjectIds for direct message passing):
 *   createWindowAbject, destroyWindowAbject,
 *   createLabel, createButton, createTextInput, createTextArea,
 *   createCheckbox, createProgress, createDivider, createSelect
 *
 * Legacy shim (for ScriptableAbjects generated by ObjectCreator):
 *   createWindow, destroyWindow, addWidget, updateWidget,
 *   removeWidget, getWidgetValue, widgetEvent
 */

import {
  AbjectId,
  AbjectMessage,
  InterfaceId,
} from '../core/types.js';
import { Abject } from '../core/abject.js';
import { require } from '../core/contracts.js';
import { request, event } from '../core/message.js';
import { INTROSPECT_INTERFACE_ID } from '../core/introspect.js';
import { WindowAbject } from './widgets/window-abject.js';
import { LabelWidget } from './widgets/label-widget.js';
import { ButtonWidget } from './widgets/button-widget.js';
import { TextInputWidget, TextInputWidgetConfig } from './widgets/text-input-widget.js';
import { TextAreaWidget, TextAreaWidgetConfig } from './widgets/text-area-widget.js';
import { CheckboxWidget, CheckboxWidgetConfig } from './widgets/checkbox-widget.js';
import { ProgressWidget, ProgressWidgetConfig } from './widgets/progress-widget.js';
import { DividerWidget } from './widgets/divider-widget.js';
import { SelectWidget, SelectWidgetConfig } from './widgets/select-widget.js';
import { WidgetAbject, WidgetConfig } from './widgets/widget-abject.js';
import { VBoxLayout } from './widgets/vbox-layout.js';
import { HBoxLayout } from './widgets/hbox-layout.js';
import { ScrollableVBoxLayout } from './widgets/scrollable-vbox-layout.js';
import { LayoutAbject, LayoutMargins } from './widgets/layout-abject.js';
import {
  WidgetType,
  WidgetStyle,
  Rect,
  ThemeData,
  MIDNIGHT_BLOOM,
  WIDGET_INTERFACE,
  WINDOW_INTERFACE,
  LAYOUT_INTERFACE,
} from './widgets/widget-types.js';

export type { WidgetStyle } from './widgets/widget-types.js';

const WIDGETS_INTERFACE: InterfaceId = 'abjects:widgets';
const UI_INTERFACE: InterfaceId = 'abjects:ui';

/**
 * WidgetManager — spawns window and widget Abjects, returns their IDs.
 */
export class WidgetManager extends Abject {
  private uiServerId?: AbjectId;
  private consoleId?: AbjectId;
  private cachedTheme: ThemeData = MIDNIGHT_BLOOM;
  private themeId?: AbjectId;
  private windowManagerId?: AbjectId;

  // Tracking spawned Abjects (Set<AbjectId>, NOT references — network transparent)
  private spawnedWindows: Set<AbjectId> = new Set();
  private spawnedWidgets: Set<AbjectId> = new Set();
  // Maps windowId → surfaceId for raiseWindow support
  private windowSurfaces: Map<AbjectId, string> = new Map();

  // Backward-compat shim: maps old string widget IDs → AbjectIds
  private shimWidgetMap: Map<string, AbjectId> = new Map();
  // Maps old windowId strings → WindowAbject AbjectIds
  private shimWindowMap: Map<string, AbjectId> = new Map();
  // Maps WindowAbject AbjectId → owning Abject
  private windowOwners: Map<AbjectId, AbjectId> = new Map();
  // Maps widget AbjectId → old-style string widget ID (for event translation)
  private widgetIdToShimId: Map<AbjectId, string> = new Map();
  // Maps widget AbjectId → window string ID (for event translation)
  private widgetToWindowShimId: Map<AbjectId, string> = new Map();

  constructor() {
    super({
      manifest: {
        name: 'WidgetManager',
        description:
          'Widget factory — spawns WindowAbject and WidgetAbject instances on the bus. Primary API returns AbjectIds for direct message passing. Legacy shim for ScriptableAbjects.',
        version: '2.0.0',
        interfaces: [
          {
            id: WIDGETS_INTERFACE,
            name: 'Widgets',
            description: 'Widget factory — spawns WindowAbject and WidgetAbject instances on the bus. ' +
              'Workflow: 1) createWindowAbject to get a window ID, 2) createVBox/createHBox to get a layout ID, ' +
              '3) create widgets (createLabel, createButton, etc.) with rect {0,0,0,0} since layout manages positioning, ' +
              '4) add widgets to layout via this.call(layoutId, "abjects:layout", "addLayoutChild", { widgetId, sizePolicy, preferredSize }), ' +
              '5) register for events via this.call(widgetId, "abjects:introspect", "addDependent", {}), ' +
              '6) handle events in a "changed" handler: { aspect, value } where aspect is "click", "change", or "submit". ' +
              'Update widgets via this.call(widgetId, "abjects:widget", "update", { text: "new text" }). ' +
              'Get values via this.call(widgetId, "abjects:widget", "getValue", {}).',
            methods: [
              {
                name: 'createWindowAbject',
                description: 'Create a window and return its AbjectId. Example: const winId = await this.call(this.dep("WidgetManager"), "abjects:widgets", "createWindowAbject", { title: "My Window", rect: { x: 100, y: 100, width: 400, height: 300 }, resizable: true })',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Window title' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height } — position and size' },
                  { name: 'zIndex', type: { kind: 'primitive', primitive: 'number' }, description: 'Z-index for stacking order', optional: true },
                  { name: 'chromeless', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, no title bar', optional: true },
                  { name: 'resizable', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, window is resizable', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'destroyWindowAbject',
                description: 'Destroy a window by its AbjectId and all its child widgets.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Window AbjectId to destroy' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'createLabel',
                description: 'Create a label widget inside a window. Returns the widget AbjectId. Update text via this.call(labelId, "abjects:widget", "update", { text: "New text" })',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Label text', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createButton',
                description: 'Create a button widget. Returns the widget AbjectId. Register via this.call(btnId, "abjects:introspect", "addDependent", {}), then handle "changed" events with aspect "click" in your changed handler.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Button label', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createTextInput',
                description: 'Create a single-line text input. Returns the widget AbjectId. Register via addDependent, listen for "changed" with aspect "change" or "submit". Get value via this.call(inputId, "abjects:widget", "getValue", {})',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Initial text', optional: true },
                  { name: 'placeholder', type: { kind: 'primitive', primitive: 'string' }, description: 'Placeholder text', optional: true },
                  { name: 'masked', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, shows dots (for passwords)', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createTextArea',
                description: 'Create a multi-line text area. Returns the widget AbjectId.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Initial text', optional: true },
                  { name: 'monospace', type: { kind: 'primitive', primitive: 'boolean' }, description: 'If true, use monospace font', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createCheckbox',
                description: 'Create a checkbox widget. Returns the widget AbjectId. Listen for "changed" events with aspect "change".',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Checkbox label', optional: true },
                  { name: 'checked', type: { kind: 'primitive', primitive: 'boolean' }, description: 'Initial checked state', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createProgress',
                description: 'Create a progress bar widget. Returns the widget AbjectId.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Label text', optional: true },
                  { name: 'value', type: { kind: 'primitive', primitive: 'number' }, description: 'Progress value (0-100)', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createDivider',
                description: 'Create a horizontal divider line. Returns the widget AbjectId.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createSelect',
                description: 'Create a dropdown select widget. Returns the widget AbjectId. Listen for "changed" events with aspect "change".',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: '{ x, y, width, height }' },
                  { name: 'text', type: { kind: 'primitive', primitive: 'string' }, description: 'Label text', optional: true },
                  { name: 'options', type: { kind: 'array', elementType: { kind: 'primitive', primitive: 'string' } }, description: 'Available options', optional: true },
                  { name: 'selectedIndex', type: { kind: 'primitive', primitive: 'number' }, description: 'Initially selected index', optional: true },
                  { name: 'style', type: { kind: 'reference', reference: 'WidgetStyle' }, description: 'Visual style overrides', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createVBox',
                description: 'Create a vertical box layout inside a window. Returns the layout AbjectId. Add children via this.call(layoutId, "abjects:layout", "addLayoutChild", { widgetId, sizePolicy: { vertical: "fixed" }, preferredSize: { height: 36 } }). Add spacers via this.call(layoutId, "abjects:layout", "addLayoutSpacer", {}).',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createHBox',
                description: 'Create a horizontal box layout inside a window. Returns the layout AbjectId. Add children via this.call(layoutId, "abjects:layout", "addLayoutChild", { widgetId, sizePolicy: { horizontal: "expanding" }, preferredSize: { width: 100, height: 36 } }).',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedVBox',
                description: 'Create a nested vertical box layout inside a parent layout. Returns the layout AbjectId.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedHBox',
                description: 'Create a nested horizontal box layout inside a parent layout. Returns the layout AbjectId.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createScrollableVBox',
                description: 'Create a scrollable vertical box layout inside a window. Returns the layout AbjectId. Content that overflows is clipped and scrollable via mouse wheel.',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent window AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'createNestedScrollableVBox',
                description: 'Create a nested scrollable vertical box layout inside a parent layout. Returns the layout AbjectId.',
                parameters: [
                  { name: 'parentLayoutId', type: { kind: 'primitive', primitive: 'string' }, description: 'Parent layout AbjectId' },
                  { name: 'margins', type: { kind: 'reference', reference: 'LayoutMargins' }, description: '{ top, right, bottom, left }', optional: true },
                  { name: 'spacing', type: { kind: 'primitive', primitive: 'number' }, description: 'Spacing between children', optional: true },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'getDisplayInfo',
                description: 'Get display dimensions (proxied from UIServer)',
                parameters: [],
                returns: {
                  kind: 'object',
                  properties: {
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
              // Legacy shim methods for backward compatibility
              {
                name: 'createWindow',
                description: '[Legacy] Create a window and return a shim string ID',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Window title' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Window position and size' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'destroyWindow',
                description: '[Legacy] Destroy a window by shim string ID',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Window shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'addWidget',
                description: '[Legacy] Add a widget to a window by shim IDs',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Target window shim ID' },
                  { name: 'id', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget identifier' },
                  { name: 'type', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget type' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Widget position' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'updateWidget',
                description: '[Legacy] Update widget properties by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                  { name: 'updates', type: { kind: 'reference', reference: 'WidgetUpdates' }, description: 'Properties to update' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'removeWidget',
                description: '[Legacy] Remove a widget by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'getWidgetValue',
                description: '[Legacy] Get widget value by shim ID',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget shim ID' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
            ],
            events: [
              {
                name: 'widgetEvent',
                description: 'Widget interaction event (click, change, submit)',
                payload: { kind: 'reference', reference: 'WMWidgetEventPayload' },
              },
              {
                name: 'windowMoved',
                description: 'Window was dragged by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    x: { kind: 'primitive', primitive: 'number' },
                    y: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
              {
                name: 'windowResized',
                description: 'Window was resized by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
            ],
          },
        ],
        requiredCapabilities: [],
        providedCapabilities: [],
        tags: ['system', 'ui'],
      },
    });

    this.setupHandlers();
  }

  private setupHandlers(): void {
    this.on('createWindow', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, resizable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        resizable?: boolean;
      };
      return this.createWindow(msg.routing.from, title, rect, { chromeless, resizable, zIndex });
    });

    this.on('destroyWindow', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: string };
      return this.destroyWindow(msg.routing.from, windowId);
    });

    // Direct factory: create window, return AbjectId (not shim string)
    this.on('createWindowAbject', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, resizable, draggable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        resizable?: boolean;
        draggable?: boolean;
      };
      return this.createWindowDirect(title, rect, { chromeless, resizable, draggable, zIndex });
    });

    // Direct factory: destroy window by AbjectId (not shim string)
    this.on('destroyWindowAbject', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: AbjectId };
      return this.destroyWindowDirect(windowId);
    });

    // ── Factory methods — create typed widget Abjects, return AbjectId ──

    this.on('createLabel', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new LabelWidget({
        type: 'label', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
      }), payload.rect);
    });

    this.on('createButton', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new ButtonWidget({
        type: 'button', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
      }), payload.rect);
    });

    this.on('createTextInput', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        placeholder?: string;
        masked?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new TextInputWidget({
        type: 'textInput', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
        placeholder: payload.placeholder, masked: payload.masked,
      }), payload.rect);
    });

    this.on('createTextArea', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        monospace?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new TextAreaWidget({
        type: 'textArea', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
        monospace: payload.monospace,
      }), payload.rect);
    });

    this.on('createCheckbox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new CheckboxWidget({
        type: 'checkbox', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
        checked: payload.checked,
      }), payload.rect);
    });

    this.on('createProgress', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        value?: number;
      };
      return this.createTypedWidget(payload.windowId, new ProgressWidget({
        type: 'progress', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
        value: payload.value,
      }), payload.rect);
    });

    this.on('createDivider', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new DividerWidget({
        type: 'divider', rect: payload.rect, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
      }), payload.rect);
    });

    this.on('createSelect', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        options?: string[];
        selectedIndex?: number;
      };
      return this.createTypedWidget(payload.windowId, new SelectWidget({
        type: 'select', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!, theme: this.cachedTheme,
        options: payload.options, selectedIndex: payload.selectedIndex,
      }), payload.rect);
    });

    // ── Layout factory methods ──

    this.on('createVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new VBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createHBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new HBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createNestedVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new VBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createNestedHBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new HBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createScrollableVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createLayoutWidget(payload.windowId, new ScrollableVBoxLayout({
        ownerId: payload.windowId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    this.on('createNestedScrollableVBox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        parentLayoutId: AbjectId;
        margins?: Partial<LayoutMargins>;
        spacing?: number;
      };
      return this.createNestedLayout(payload.parentLayoutId, new ScrollableVBoxLayout({
        ownerId: payload.parentLayoutId,
        uiServerId: this.uiServerId!,
        margins: payload.margins,
        spacing: payload.spacing,
      }));
    });

    // ── Shim methods (backward compat) ──

    this.on('addWidget', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: string;
        id: string;
        type: WidgetType;
        rect: { x: number; y: number; width: number; height: number };
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        placeholder?: string;
        monospace?: boolean;
        masked?: boolean;
      };
      return this.addWidget(msg.routing.from, payload);
    });

    this.on('updateWidget', async (msg: AbjectMessage) => {
      const { widgetId, ...updates } = msg.payload as {
        widgetId: string;
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        rect?: { x: number; y: number; width: number; height: number };
        masked?: boolean;
      };
      return this.updateWidget(widgetId, updates);
    });

    this.on('removeWidget', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.removeWidget(widgetId);
    });

    this.on('getWidgetValue', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.getWidgetValue(widgetId);
    });

    this.on('getDisplayInfo', async () => {
      require(this.uiServerId !== undefined, 'UIServer not set');
      return this.request<{ width: number; height: number }>(
        request(this.id, this.uiServerId!, UI_INTERFACE, 'getDisplayInfo', {})
      );
    });

    this.on('raiseWindow', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: AbjectId };
      if (!this.windowManagerId) return false;
      const surfaceId = this.windowSurfaces.get(windowId);
      if (!surfaceId) return false;
      return this.request(request(this.id, this.windowManagerId,
        'abjects:window-manager' as InterfaceId, 'raiseWindow', { surfaceId }));
    });

    // Handle 'changed' events from widget Abjects (dependency protocol)
    this.on('changed', async (msg: AbjectMessage) => {
      const { aspect, value } = msg.payload as { aspect: string; value?: unknown };
      const fromId = msg.routing.from;

      // Handle theme changes from ThemeAbject
      if (aspect === 'themeChanged' && fromId === this.themeId) {
        this.cachedTheme = value as ThemeData;
        // Propagate to all spawned widgets
        for (const id of this.spawnedWidgets) {
          try {
            await this.send(
              request(this.id, id, WIDGET_INTERFACE, 'updateTheme', this.cachedTheme)
            );
          } catch { /* widget gone */ }
        }
        // Propagate to all spawned windows
        for (const id of this.spawnedWindows) {
          try {
            await this.send(
              request(this.id, id, WINDOW_INTERFACE, 'updateTheme', this.cachedTheme)
            );
          } catch { /* window gone */ }
        }
        return;
      }

      // Translate widget changed events to old-style widgetEvent messages
      const shimId = this.widgetIdToShimId.get(fromId);
      const windowShimId = this.widgetToWindowShimId.get(fromId);
      if (!shimId || !windowShimId) return;

      // Find the window's owner
      const windowAbjectId = this.shimWindowMap.get(windowShimId);
      if (!windowAbjectId) return;
      const ownerId = this.windowOwners.get(windowAbjectId);
      if (!ownerId) return;

      // Map aspect to old-style event type
      let eventType: 'click' | 'change' | 'submit' | undefined;
      if (aspect === 'click') eventType = 'click';
      else if (aspect === 'change') eventType = 'change';
      else if (aspect === 'submit') eventType = 'submit';

      if (eventType) {
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'widgetEvent', {
            windowId: windowShimId,
            widgetId: shimId,
            type: eventType,
            value: value !== undefined ? String(value) : undefined,
          })
        );
      }

      // Forward window events
      if (aspect === 'windowRect') {
        const { x, y, width, height } = value as { x: number; y: number; width: number; height: number };
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowMoved', { windowId: windowShimId, x, y })
        );
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowResized', { windowId: windowShimId, width, height })
        );
      }
      if (aspect === 'windowMoved') {
        const { x, y } = value as { x: number; y: number };
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowMoved', { windowId: windowShimId, x, y })
        );
      }
      if (aspect === 'windowResized') {
        const { width, height } = value as { width: number; height: number };
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowResized', { windowId: windowShimId, width, height })
        );
      }
    });
  }

  protected override async onInit(): Promise<void> {
    this.uiServerId = await this.requireDep('UIServer');
    this.consoleId = await this.discoverDep('Console') ?? undefined;
    this.windowManagerId = await this.discoverDep('WindowManager') ?? undefined;

    // Query ThemeAbject for the current theme
    this.themeId = await this.discoverDep('Theme') ?? undefined;
    if (this.themeId) {
      try {
        const theme = await this.request<ThemeData>(
          request(this.id, this.themeId, 'abjects:theme' as InterfaceId, 'getTheme', {})
        );
        if (theme && typeof theme === 'object' && 'canvasBg' in theme) {
          this.cachedTheme = theme;
        }
      } catch {
        // Theme not available — use default
      }

      // Register as dependent to receive theme change notifications
      try {
        await this.request(
          request(this.id, this.themeId, INTROSPECT_INTERFACE_ID, 'addDependent', {})
        );
      } catch {
        // Theme may not support dependents
      }
    }
  }

  private async log(level: string, message: string, data?: unknown): Promise<void> {
    if (!this.consoleId) return;
    try {
      await this.send(
        request(this.id, this.consoleId, 'abjects:console' as InterfaceId, level, { message, data })
      );
    } catch { /* logging should never break the caller */ }
  }

  protected override getSourceForAsk(): string | undefined {
    return `## WidgetManager Usage Guide

### Complete Workflow Example

// 1. Create a window
const winId = await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'createWindowAbject', {
  title: 'My Window', rect: { x: 100, y: 100, width: 400, height: 300 }, resizable: true
});

// 2. Create a vertical layout
const layoutId = await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'createVBox', {
  windowId: winId, margins: { top: 8, right: 16, bottom: 8, left: 16 }, spacing: 8
});

// 3. Create widgets
const labelId = await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'createLabel', {
  windowId: winId, rect: { x: 0, y: 0, width: 0, height: 0 }, text: 'Hello World'
});

const btnId = await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'createButton', {
  windowId: winId, rect: { x: 0, y: 0, width: 0, height: 0 }, text: 'Click Me'
});

const inputId = await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'createTextInput', {
  windowId: winId, rect: { x: 0, y: 0, width: 0, height: 0 }, placeholder: 'Type here...'
});

// 4. Add widgets to layout (rect can be {0,0,0,0} — layout manages positioning)
await this.call(layoutId, 'abjects:layout', 'addLayoutChild', {
  widgetId: labelId, sizePolicy: { vertical: 'fixed' }, preferredSize: { height: 20 }
});
await this.call(layoutId, 'abjects:layout', 'addLayoutChild', {
  widgetId: inputId, sizePolicy: { vertical: 'fixed', horizontal: 'expanding' }, preferredSize: { height: 36 }
});
await this.call(layoutId, 'abjects:layout', 'addLayoutChild', {
  widgetId: btnId, sizePolicy: { horizontal: 'fixed' }, preferredSize: { width: 100, height: 36 }
});

// Add a spacer to push widgets apart:
await this.call(layoutId, 'abjects:layout', 'addLayoutSpacer', {});

// 5. Register for button click events
await this.call(btnId, 'abjects:introspect', 'addDependent', {});

// 6. Handle events — implement a 'changed' handler in your handler map:
async changed(msg) {
  const { aspect, value } = msg.payload;
  const fromId = msg.routing.from;
  if (fromId === this._btnId && aspect === 'click') {
    // Button was clicked
  }
  if (fromId === this._inputId && aspect === 'submit') {
    // Enter pressed in text input
  }
}

### Updating Widgets

// Update label text:
await this.call(labelId, 'abjects:widget', 'update', { text: 'New text' });

// Get text input value:
const value = await this.call(inputId, 'abjects:widget', 'getValue', {});

### Destroying a Window

await this.call(this.dep('WidgetManager'), 'abjects:widgets', 'destroyWindowAbject', { windowId: winId });

### Available Widget Types

createLabel - Static text display
createButton - Clickable button (listen for 'changed' with aspect 'click')
createTextInput - Single-line text input (aspects: 'change', 'submit')
createTextArea - Multi-line text area (params: monospace?)
createCheckbox - Toggle checkbox (aspect: 'change', value: boolean)
createProgress - Progress bar (update with { value: 0-100 })
createDivider - Horizontal divider line
createSelect - Dropdown select (params: options[], selectedIndex)

### Layout Types

createVBox - Vertical stack layout
createHBox - Horizontal row layout
createNestedVBox - Nested vertical layout inside another layout
createNestedHBox - Nested horizontal layout inside another layout

### Interface IDs

'abjects:widgets' - WidgetManager factory methods
'abjects:widget' - Widget instance methods (update, getValue)
'abjects:layout' - Layout methods (addLayoutChild, addLayoutSpacer)
'abjects:window' - Window methods
'abjects:introspect' - For addDependent (event registration)`;
  }

  // ── Factory: createWindow ─────────────────────────────────────────────

  private async createWindow(
    owner: AbjectId,
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; resizable?: boolean; zIndex?: number }
  ): Promise<string> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      resizable: options?.resizable,
      zIndex: options?.zIndex ?? 100,
      theme: this.cachedTheme,
    });

    await win.init(this.bus, this.id);
    this.spawnedWindows.add(win.id);

    // Register as dependent of the window (for windowMoved/windowResized events)
    await this.request(
      request(this.id, win.id, INTROSPECT_INTERFACE_ID, 'addDependent', {})
    );

    // Register with WindowManager for z-order and drag/resize management
    if (this.windowManagerId && win.surface) {
      try {
        await this.request(request(this.id, this.windowManagerId,
          'abjects:window-manager' as InterfaceId, 'registerWindow', {
            surfaceId: win.surface, windowId: win.id, zIndex: options?.zIndex ?? 100,
            rect, chromeless: options?.chromeless ?? false,
            draggable: false,
          }));
      } catch { /* WindowManager may not be ready */ }
    }

    // Generate a shim window ID for backward compat
    const shimWindowId = `wm-win-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    this.shimWindowMap.set(shimWindowId, win.id);
    this.windowOwners.set(win.id, owner);

    return shimWindowId;
  }

  // ── Factory: createWindowDirect — returns AbjectId ──────────────────

  private async createWindowDirect(
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; resizable?: boolean; draggable?: boolean; zIndex?: number }
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      resizable: options?.resizable,
      draggable: options?.draggable,
      zIndex: options?.zIndex ?? 100,
      theme: this.cachedTheme,
    });

    await win.init(this.bus, this.id);
    this.spawnedWindows.add(win.id);
    if (win.surface) this.windowSurfaces.set(win.id, win.surface);
    this.log('debug', 'createWindowAbject', { windowId: win.id, title });

    // Register with WindowManager for z-order and drag/resize management
    if (this.windowManagerId && win.surface) {
      try {
        await this.request(request(this.id, this.windowManagerId,
          'abjects:window-manager' as InterfaceId, 'registerWindow', {
            surfaceId: win.surface, windowId: win.id, zIndex: options?.zIndex ?? 100,
            rect, chromeless: options?.chromeless ?? false,
            draggable: options?.draggable ?? false,
          }));
      } catch { /* WindowManager may not be ready */ }
    }

    return win.id;
  }

  // ── Factory: destroyWindowDirect — destroy by AbjectId ─────────────

  private async destroyWindowDirect(windowId: AbjectId): Promise<boolean> {
    if (!this.spawnedWindows.has(windowId)) return false;
    console.debug(`[WidgetManager] destroyWindowDirect(${windowId})`);

    // Unregister from WindowManager
    if (this.windowManagerId) {
      try {
        this.send(event(this.id, this.windowManagerId,
          'abjects:window-manager' as InterfaceId, 'unregisterWindow', { windowId }));
      } catch { /* WM may be gone */ }
    }

    try {
      console.debug(`[WidgetManager] sending destroy request to WindowAbject ${windowId}`);
      await this.request(
        request(this.id, windowId, WINDOW_INTERFACE, 'destroy', {})
      );
      console.debug(`[WidgetManager] WindowAbject ${windowId} destroyed`);
    } catch {
      // Window may already be stopped
    }

    this.spawnedWindows.delete(windowId);
    this.windowSurfaces.delete(windowId);
    return true;
  }

  // ── Factory: createLayoutWidget — init layout and add as window child ──

  private async createLayoutWidget(
    windowId: AbjectId,
    layout: LayoutAbject
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await layout.init(this.bus, this.id);
    this.spawnedWidgets.add(layout.id);

    // Add the layout as the window's child with a full-content rect
    // The window will update this rect on resize
    await this.request(
      request(this.id, windowId, WINDOW_INTERFACE, 'addChild', {
        widgetId: layout.id,
        rect: { x: 0, y: 0, width: 0, height: 0 },
      })
    );

    return layout.id;
  }

  // ── Factory: createNestedLayout — init layout and add to parent layout ──

  private async createNestedLayout(
    parentLayoutId: AbjectId,
    layout: LayoutAbject
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await layout.init(this.bus, this.id);
    this.spawnedWidgets.add(layout.id);

    return layout.id;
  }

  // ── Factory: createTypedWidget (shared helper for factory methods) ───

  private async createTypedWidget(
    windowId: AbjectId,
    widget: WidgetAbject,
    rect: Rect
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await widget.init(this.bus, this.id);
    this.spawnedWidgets.add(widget.id);
    this.log('debug', 'createWidget', { widgetId: widget.id, windowId, type: widget.manifest.name });

    // Only add to window if rect is non-zero.
    // Layout-managed widgets pass {0,0,0,0} and are positioned by their layout.
    if (rect.width > 0 || rect.height > 0) {
      await this.request(
        request(this.id, windowId, WINDOW_INTERFACE, 'addChild', {
          widgetId: widget.id,
          rect,
        })
      );
    }

    return widget.id;
  }

  // ── Factory: destroyWindow ────────────────────────────────────────────

  private async destroyWindow(owner: AbjectId, windowId: string): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(windowId);
    if (!winAbjectId) return false;

    // Verify ownership
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    // Unregister from WindowManager
    if (this.windowManagerId) {
      try {
        this.send(event(this.id, this.windowManagerId,
          'abjects:window-manager' as InterfaceId, 'unregisterWindow', { windowId: winAbjectId }));
      } catch { /* WM may be gone */ }
    }

    // Send destroy message to WindowAbject (it will destroy all children)
    try {
      await this.request(
        request(this.id, winAbjectId, WINDOW_INTERFACE, 'destroy', {})
      );
    } catch {
      // Window may already be stopped
    }

    // Clean up shim maps
    this.shimWindowMap.delete(windowId);
    this.windowOwners.delete(winAbjectId);
    this.spawnedWindows.delete(winAbjectId);

    // Clean up widget shim entries for this window
    for (const [shimId, abjectId] of this.shimWidgetMap.entries()) {
      if (this.widgetToWindowShimId.get(abjectId) === windowId) {
        this.shimWidgetMap.delete(shimId);
        this.widgetIdToShimId.delete(abjectId);
        this.widgetToWindowShimId.delete(abjectId);
        this.spawnedWidgets.delete(abjectId);
      }
    }

    return true;
  }

  // ── Shim: addWidget ───────────────────────────────────────────────────

  private async addWidget(
    owner: AbjectId,
    config: {
      windowId: string;
      id: string;
      type: WidgetType;
      rect: { x: number; y: number; width: number; height: number };
      text?: string;
      style?: WidgetStyle;
      checked?: boolean;
      value?: number;
      options?: string[];
      selectedIndex?: number;
      placeholder?: string;
      monospace?: boolean;
      masked?: boolean;
    }
  ): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(config.windowId);
    if (!winAbjectId) return false;
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    require(this.uiServerId !== undefined, 'UIServer not set');

    // Create the appropriate widget Abject
    const baseConfig: WidgetConfig = {
      type: config.type,
      rect: config.rect,
      text: config.text,
      style: config.style,
      ownerId: winAbjectId,
      uiServerId: this.uiServerId!,
      theme: this.cachedTheme,
    };

    let widget: WidgetAbject;

    switch (config.type) {
      case 'label':
        widget = new LabelWidget(baseConfig);
        break;
      case 'button':
        widget = new ButtonWidget(baseConfig);
        break;
      case 'textInput':
        widget = new TextInputWidget({
          ...baseConfig,
          placeholder: config.placeholder,
          masked: config.masked,
        } as TextInputWidgetConfig);
        break;
      case 'textArea':
        widget = new TextAreaWidget({
          ...baseConfig,
          monospace: config.monospace,
        } as TextAreaWidgetConfig);
        break;
      case 'checkbox':
        widget = new CheckboxWidget({
          ...baseConfig,
          checked: config.checked,
        } as CheckboxWidgetConfig);
        break;
      case 'progress':
        widget = new ProgressWidget({
          ...baseConfig,
          value: config.value,
        } as ProgressWidgetConfig);
        break;
      case 'divider':
        widget = new DividerWidget(baseConfig);
        break;
      case 'select':
        widget = new SelectWidget({
          ...baseConfig,
          options: config.options,
          selectedIndex: config.selectedIndex,
        } as SelectWidgetConfig);
        break;
      default:
        return false;
    }

    await widget.init(this.bus, this.id);
    this.spawnedWidgets.add(widget.id);

    // Register WidgetManager as dependent of the widget (for event translation)
    await this.request(
      request(this.id, widget.id, INTROSPECT_INTERFACE_ID, 'addDependent', {})
    );

    // Track shim mappings
    this.shimWidgetMap.set(config.id, widget.id);
    this.widgetIdToShimId.set(widget.id, config.id);
    this.widgetToWindowShimId.set(widget.id, config.windowId);

    // Tell the WindowAbject to add this child
    await this.request(
      request(this.id, winAbjectId, WINDOW_INTERFACE, 'addChild', {
        widgetId: widget.id,
        rect: config.rect,
      })
    );

    return true;
  }

  // ── Shim: updateWidget ────────────────────────────────────────────────

  private async updateWidget(
    widgetId: string,
    updates: Record<string, unknown>
  ): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    try {
      await this.request(
        request(this.id, abjectId, WIDGET_INTERFACE, 'update', updates)
      );
      return true;
    } catch {
      return false;
    }
  }

  // ── Shim: removeWidget ────────────────────────────────────────────────

  private async removeWidget(widgetId: string): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    const windowShimId = this.widgetToWindowShimId.get(abjectId);
    if (windowShimId) {
      const winAbjectId = this.shimWindowMap.get(windowShimId);
      if (winAbjectId) {
        try {
          await this.request(
            request(this.id, winAbjectId, WINDOW_INTERFACE, 'removeChild', { widgetId: abjectId })
          );
        } catch {
          // Window may be gone
        }
      }
    }

    // Destroy the widget (must use request() so the reply is consumed)
    try {
      await this.request(request(this.id, abjectId, WIDGET_INTERFACE, 'destroy', {}));
    } catch {
      // Widget may be gone
    }

    this.shimWidgetMap.delete(widgetId);
    this.widgetIdToShimId.delete(abjectId);
    this.widgetToWindowShimId.delete(abjectId);
    this.spawnedWidgets.delete(abjectId);

    return true;
  }

  // ── Shim: getWidgetValue ──────────────────────────────────────────────

  private async getWidgetValue(widgetId: string): Promise<string> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return '';

    try {
      return await this.request<string>(
        request(this.id, abjectId, WIDGET_INTERFACE, 'getValue', {})
      );
    } catch {
      return '';
    }
  }
}

// Well-known WidgetManager ID
export const WIDGET_MANAGER_ID = 'abjects:widget-manager' as AbjectId;
