/**
 * Widget Manager — factory that spawns WindowAbject and WidgetAbject instances.
 *
 * WidgetManager is a thin factory. It spawns widget Abjects on the bus and
 * returns their AbjectIds. All rendering, input handling, and state management
 * lives in the widget Abjects themselves.
 *
 * Primary API (returns AbjectIds for direct message passing):
 *   createWindowAbject, destroyWindowAbject,
 *   createLabel, createButton, createTextInput, createTextArea,
 *   createCheckbox, createProgress, createDivider, createSelect
 *
 * Legacy shim (for ScriptableAbjects generated by ObjectCreator):
 *   createWindow, destroyWindow, addWidget, updateWidget,
 *   removeWidget, getWidgetValue, widgetEvent
 */

import {
  AbjectId,
  AbjectMessage,
  InterfaceId,
} from '../core/types.js';
import { Abject } from '../core/abject.js';
import { require } from '../core/contracts.js';
import { request, event } from '../core/message.js';
import { INTROSPECT_INTERFACE_ID } from '../core/introspect.js';
import { WindowAbject } from './widgets/window-abject.js';
import { LabelWidget } from './widgets/label-widget.js';
import { ButtonWidget } from './widgets/button-widget.js';
import { TextInputWidget, TextInputWidgetConfig } from './widgets/text-input-widget.js';
import { TextAreaWidget, TextAreaWidgetConfig } from './widgets/text-area-widget.js';
import { CheckboxWidget, CheckboxWidgetConfig } from './widgets/checkbox-widget.js';
import { ProgressWidget, ProgressWidgetConfig } from './widgets/progress-widget.js';
import { DividerWidget } from './widgets/divider-widget.js';
import { SelectWidget, SelectWidgetConfig } from './widgets/select-widget.js';
import { WidgetAbject, WidgetConfig } from './widgets/widget-abject.js';
import {
  WidgetType,
  WidgetStyle,
  Rect,
  WIDGET_INTERFACE,
  WINDOW_INTERFACE,
} from './widgets/widget-types.js';

export type { WidgetStyle } from './widgets/widget-types.js';

const WIDGETS_INTERFACE: InterfaceId = 'abjects:widgets';
const UI_INTERFACE: InterfaceId = 'abjects:ui';

/**
 * WidgetManager — spawns window and widget Abjects, returns their IDs.
 */
export class WidgetManager extends Abject {
  private uiServerId?: AbjectId;

  // Tracking spawned Abjects (Set<AbjectId>, NOT references — network transparent)
  private spawnedWindows: Set<AbjectId> = new Set();
  private spawnedWidgets: Set<AbjectId> = new Set();

  // Backward-compat shim: maps old string widget IDs → AbjectIds
  private shimWidgetMap: Map<string, AbjectId> = new Map();
  // Maps old windowId strings → WindowAbject AbjectIds
  private shimWindowMap: Map<string, AbjectId> = new Map();
  // Maps WindowAbject AbjectId → owning Abject
  private windowOwners: Map<AbjectId, AbjectId> = new Map();
  // Maps widget AbjectId → old-style string widget ID (for event translation)
  private widgetIdToShimId: Map<AbjectId, string> = new Map();
  // Maps widget AbjectId → window string ID (for event translation)
  private widgetToWindowShimId: Map<AbjectId, string> = new Map();

  constructor() {
    super({
      manifest: {
        name: 'WidgetManager',
        description:
          'Widget factory — spawns WindowAbject and WidgetAbject instances on the bus. Primary API returns AbjectIds for direct message passing. Legacy shim for ScriptableAbjects.',
        version: '2.0.0',
        interfaces: [
          {
            id: WIDGETS_INTERFACE,
            name: 'Widgets',
            description: 'Window and widget management (factory + shim)',
            methods: [
              {
                name: 'createWindow',
                description: 'Create a managed window (spawns WindowAbject)',
                parameters: [
                  { name: 'title', type: { kind: 'primitive', primitive: 'string' }, description: 'Window title' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Window position and size' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'destroyWindow',
                description: 'Destroy a window and all its widgets',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Window to destroy' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'addWidget',
                description: 'Add a widget to a window (backward-compatible shim)',
                parameters: [
                  { name: 'windowId', type: { kind: 'primitive', primitive: 'string' }, description: 'Target window' },
                  { name: 'id', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget identifier' },
                  { name: 'type', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget type' },
                  { name: 'rect', type: { kind: 'reference', reference: 'Rect' }, description: 'Widget position' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'updateWidget',
                description: 'Update widget properties (backward-compatible shim)',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget ID' },
                  { name: 'updates', type: { kind: 'reference', reference: 'WidgetUpdates' }, description: 'Properties to update' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'removeWidget',
                description: 'Remove a single widget',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget to remove' },
                ],
                returns: { kind: 'primitive', primitive: 'boolean' },
              },
              {
                name: 'getWidgetValue',
                description: 'Get the current value of a widget (backward-compatible shim)',
                parameters: [
                  { name: 'widgetId', type: { kind: 'primitive', primitive: 'string' }, description: 'Widget ID' },
                ],
                returns: { kind: 'primitive', primitive: 'string' },
              },
              {
                name: 'getDisplayInfo',
                description: 'Get display dimensions (proxied from UIServer)',
                parameters: [],
                returns: {
                  kind: 'object',
                  properties: {
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
            ],
            events: [
              {
                name: 'widgetEvent',
                description: 'Widget interaction event (click, change, submit)',
                payload: { kind: 'reference', reference: 'WMWidgetEventPayload' },
              },
              {
                name: 'windowMoved',
                description: 'Window was dragged by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    x: { kind: 'primitive', primitive: 'number' },
                    y: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
              {
                name: 'windowResized',
                description: 'Window was resized by the user',
                payload: {
                  kind: 'object',
                  properties: {
                    windowId: { kind: 'primitive', primitive: 'string' },
                    width: { kind: 'primitive', primitive: 'number' },
                    height: { kind: 'primitive', primitive: 'number' },
                  },
                },
              },
            ],
          },
        ],
        requiredCapabilities: [],
        providedCapabilities: [],
        tags: ['system', 'ui'],
      },
    });

    this.setupHandlers();
  }

  private setupHandlers(): void {
    this.on('createWindow', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, resizable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        resizable?: boolean;
      };
      return this.createWindow(msg.routing.from, title, rect, { chromeless, resizable, zIndex });
    });

    this.on('destroyWindow', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: string };
      return this.destroyWindow(msg.routing.from, windowId);
    });

    // Direct factory: create window, return AbjectId (not shim string)
    this.on('createWindowAbject', async (msg: AbjectMessage) => {
      const { title, rect, zIndex, chromeless, resizable } = msg.payload as {
        title: string;
        rect: { x: number; y: number; width: number; height: number };
        zIndex?: number;
        chromeless?: boolean;
        resizable?: boolean;
      };
      return this.createWindowDirect(title, rect, { chromeless, resizable, zIndex });
    });

    // Direct factory: destroy window by AbjectId (not shim string)
    this.on('destroyWindowAbject', async (msg: AbjectMessage) => {
      const { windowId } = msg.payload as { windowId: AbjectId };
      return this.destroyWindowDirect(windowId);
    });

    // ── Factory methods — create typed widget Abjects, return AbjectId ──

    this.on('createLabel', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new LabelWidget({
        type: 'label', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
      }), payload.rect);
    });

    this.on('createButton', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new ButtonWidget({
        type: 'button', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
      }), payload.rect);
    });

    this.on('createTextInput', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        placeholder?: string;
        masked?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new TextInputWidget({
        type: 'textInput', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
        placeholder: payload.placeholder, masked: payload.masked,
      }), payload.rect);
    });

    this.on('createTextArea', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        monospace?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new TextAreaWidget({
        type: 'textArea', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
        monospace: payload.monospace,
      }), payload.rect);
    });

    this.on('createCheckbox', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
      };
      return this.createTypedWidget(payload.windowId, new CheckboxWidget({
        type: 'checkbox', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
        checked: payload.checked,
      }), payload.rect);
    });

    this.on('createProgress', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        value?: number;
      };
      return this.createTypedWidget(payload.windowId, new ProgressWidget({
        type: 'progress', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
        value: payload.value,
      }), payload.rect);
    });

    this.on('createDivider', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        style?: WidgetStyle;
      };
      return this.createTypedWidget(payload.windowId, new DividerWidget({
        type: 'divider', rect: payload.rect, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
      }), payload.rect);
    });

    this.on('createSelect', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: AbjectId;
        rect: Rect;
        text?: string;
        style?: WidgetStyle;
        options?: string[];
        selectedIndex?: number;
      };
      return this.createTypedWidget(payload.windowId, new SelectWidget({
        type: 'select', rect: payload.rect, text: payload.text, style: payload.style,
        ownerId: payload.windowId, uiServerId: this.uiServerId!,
        options: payload.options, selectedIndex: payload.selectedIndex,
      }), payload.rect);
    });

    // ── Shim methods (backward compat) ──

    this.on('addWidget', async (msg: AbjectMessage) => {
      const payload = msg.payload as {
        windowId: string;
        id: string;
        type: WidgetType;
        rect: { x: number; y: number; width: number; height: number };
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        placeholder?: string;
        monospace?: boolean;
        masked?: boolean;
      };
      return this.addWidget(msg.routing.from, payload);
    });

    this.on('updateWidget', async (msg: AbjectMessage) => {
      const { widgetId, ...updates } = msg.payload as {
        widgetId: string;
        text?: string;
        style?: WidgetStyle;
        checked?: boolean;
        value?: number;
        options?: string[];
        selectedIndex?: number;
        rect?: { x: number; y: number; width: number; height: number };
        masked?: boolean;
      };
      return this.updateWidget(widgetId, updates);
    });

    this.on('removeWidget', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.removeWidget(widgetId);
    });

    this.on('getWidgetValue', async (msg: AbjectMessage) => {
      const { widgetId } = msg.payload as { widgetId: string };
      return this.getWidgetValue(widgetId);
    });

    this.on('getDisplayInfo', async () => {
      require(this.uiServerId !== undefined, 'UIServer not set');
      return this.request<{ width: number; height: number }>(
        request(this.id, this.uiServerId!, UI_INTERFACE, 'getDisplayInfo', {})
      );
    });

    // Handle 'changed' events from widget Abjects (dependency protocol)
    this.on('changed', async (msg: AbjectMessage) => {
      const { aspect, value } = msg.payload as { aspect: string; value?: unknown };
      const fromId = msg.routing.from;

      // Translate widget changed events to old-style widgetEvent messages
      const shimId = this.widgetIdToShimId.get(fromId);
      const windowShimId = this.widgetToWindowShimId.get(fromId);
      if (!shimId || !windowShimId) return;

      // Find the window's owner
      const windowAbjectId = this.shimWindowMap.get(windowShimId);
      if (!windowAbjectId) return;
      const ownerId = this.windowOwners.get(windowAbjectId);
      if (!ownerId) return;

      // Map aspect to old-style event type
      let eventType: 'click' | 'change' | 'submit' | undefined;
      if (aspect === 'click') eventType = 'click';
      else if (aspect === 'change') eventType = 'change';
      else if (aspect === 'submit') eventType = 'submit';

      if (eventType) {
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'widgetEvent', {
            windowId: windowShimId,
            widgetId: shimId,
            type: eventType,
            value: value !== undefined ? String(value) : undefined,
          })
        );
      }

      // Forward window events
      if (aspect === 'windowMoved') {
        const { x, y } = value as { x: number; y: number };
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowMoved', { windowId: windowShimId, x, y })
        );
      }
      if (aspect === 'windowResized') {
        const { width, height } = value as { width: number; height: number };
        await this.send(
          event(this.id, ownerId, WIDGETS_INTERFACE, 'windowResized', { windowId: windowShimId, width, height })
        );
      }
    });
  }

  /**
   * Set the UIServer dependency.
   */
  setDependencies(uiServerId: AbjectId): void {
    this.uiServerId = uiServerId;
  }

  // ── Factory: createWindow ─────────────────────────────────────────────

  private async createWindow(
    owner: AbjectId,
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; resizable?: boolean; zIndex?: number }
  ): Promise<string> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      resizable: options?.resizable,
      zIndex: options?.zIndex ?? 100,
    });

    await win.init(this.bus);
    this.spawnedWindows.add(win.id);

    // Register as dependent of the window (for windowMoved/windowResized events)
    await this.request(
      request(this.id, win.id, INTROSPECT_INTERFACE_ID, 'addDependent', {})
    );

    // Generate a shim window ID for backward compat
    const shimWindowId = `wm-win-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    this.shimWindowMap.set(shimWindowId, win.id);
    this.windowOwners.set(win.id, owner);

    return shimWindowId;
  }

  // ── Factory: createWindowDirect — returns AbjectId ──────────────────

  private async createWindowDirect(
    title: string,
    rect: { x: number; y: number; width: number; height: number },
    options?: { chromeless?: boolean; resizable?: boolean; zIndex?: number }
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    const win = new WindowAbject({
      title,
      rect,
      uiServerId: this.uiServerId!,
      chromeless: options?.chromeless,
      resizable: options?.resizable,
      zIndex: options?.zIndex ?? 100,
    });

    await win.init(this.bus);
    this.spawnedWindows.add(win.id);
    return win.id;
  }

  // ── Factory: destroyWindowDirect — destroy by AbjectId ─────────────

  private async destroyWindowDirect(windowId: AbjectId): Promise<boolean> {
    if (!this.spawnedWindows.has(windowId)) return false;

    try {
      await this.request(
        request(this.id, windowId, WINDOW_INTERFACE, 'destroy', {})
      );
    } catch {
      // Window may already be stopped
    }

    this.spawnedWindows.delete(windowId);
    return true;
  }

  // ── Factory: createTypedWidget (shared helper for factory methods) ───

  private async createTypedWidget(
    windowId: AbjectId,
    widget: WidgetAbject,
    rect: Rect
  ): Promise<AbjectId> {
    require(this.uiServerId !== undefined, 'UIServer not set');

    await widget.init(this.bus);
    this.spawnedWidgets.add(widget.id);

    // Tell the WindowAbject to add this child
    await this.request(
      request(this.id, windowId, WINDOW_INTERFACE, 'addChild', {
        widgetId: widget.id,
        rect,
      })
    );

    return widget.id;
  }

  // ── Factory: destroyWindow ────────────────────────────────────────────

  private async destroyWindow(owner: AbjectId, windowId: string): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(windowId);
    if (!winAbjectId) return false;

    // Verify ownership
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    // Send destroy message to WindowAbject (it will destroy all children)
    try {
      await this.request(
        request(this.id, winAbjectId, WINDOW_INTERFACE, 'destroy', {})
      );
    } catch {
      // Window may already be stopped
    }

    // Clean up shim maps
    this.shimWindowMap.delete(windowId);
    this.windowOwners.delete(winAbjectId);
    this.spawnedWindows.delete(winAbjectId);

    // Clean up widget shim entries for this window
    for (const [shimId, abjectId] of this.shimWidgetMap.entries()) {
      if (this.widgetToWindowShimId.get(abjectId) === windowId) {
        this.shimWidgetMap.delete(shimId);
        this.widgetIdToShimId.delete(abjectId);
        this.widgetToWindowShimId.delete(abjectId);
        this.spawnedWidgets.delete(abjectId);
      }
    }

    return true;
  }

  // ── Shim: addWidget ───────────────────────────────────────────────────

  private async addWidget(
    owner: AbjectId,
    config: {
      windowId: string;
      id: string;
      type: WidgetType;
      rect: { x: number; y: number; width: number; height: number };
      text?: string;
      style?: WidgetStyle;
      checked?: boolean;
      value?: number;
      options?: string[];
      selectedIndex?: number;
      placeholder?: string;
      monospace?: boolean;
      masked?: boolean;
    }
  ): Promise<boolean> {
    const winAbjectId = this.shimWindowMap.get(config.windowId);
    if (!winAbjectId) return false;
    if (this.windowOwners.get(winAbjectId) !== owner) return false;

    require(this.uiServerId !== undefined, 'UIServer not set');

    // Create the appropriate widget Abject
    const baseConfig: WidgetConfig = {
      type: config.type,
      rect: config.rect,
      text: config.text,
      style: config.style,
      ownerId: winAbjectId,
      uiServerId: this.uiServerId!,
    };

    let widget: WidgetAbject;

    switch (config.type) {
      case 'label':
        widget = new LabelWidget(baseConfig);
        break;
      case 'button':
        widget = new ButtonWidget(baseConfig);
        break;
      case 'textInput':
        widget = new TextInputWidget({
          ...baseConfig,
          placeholder: config.placeholder,
          masked: config.masked,
        } as TextInputWidgetConfig);
        break;
      case 'textArea':
        widget = new TextAreaWidget({
          ...baseConfig,
          monospace: config.monospace,
        } as TextAreaWidgetConfig);
        break;
      case 'checkbox':
        widget = new CheckboxWidget({
          ...baseConfig,
          checked: config.checked,
        } as CheckboxWidgetConfig);
        break;
      case 'progress':
        widget = new ProgressWidget({
          ...baseConfig,
          value: config.value,
        } as ProgressWidgetConfig);
        break;
      case 'divider':
        widget = new DividerWidget(baseConfig);
        break;
      case 'select':
        widget = new SelectWidget({
          ...baseConfig,
          options: config.options,
          selectedIndex: config.selectedIndex,
        } as SelectWidgetConfig);
        break;
      default:
        return false;
    }

    await widget.init(this.bus);
    this.spawnedWidgets.add(widget.id);

    // Register WidgetManager as dependent of the widget (for event translation)
    await this.request(
      request(this.id, widget.id, INTROSPECT_INTERFACE_ID, 'addDependent', {})
    );

    // Track shim mappings
    this.shimWidgetMap.set(config.id, widget.id);
    this.widgetIdToShimId.set(widget.id, config.id);
    this.widgetToWindowShimId.set(widget.id, config.windowId);

    // Tell the WindowAbject to add this child
    await this.request(
      request(this.id, winAbjectId, WINDOW_INTERFACE, 'addChild', {
        widgetId: widget.id,
        rect: config.rect,
      })
    );

    return true;
  }

  // ── Shim: updateWidget ────────────────────────────────────────────────

  private async updateWidget(
    widgetId: string,
    updates: Record<string, unknown>
  ): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    try {
      await this.request(
        request(this.id, abjectId, WIDGET_INTERFACE, 'update', updates)
      );
      return true;
    } catch {
      return false;
    }
  }

  // ── Shim: removeWidget ────────────────────────────────────────────────

  private async removeWidget(widgetId: string): Promise<boolean> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return false;

    const windowShimId = this.widgetToWindowShimId.get(abjectId);
    if (windowShimId) {
      const winAbjectId = this.shimWindowMap.get(windowShimId);
      if (winAbjectId) {
        try {
          await this.request(
            request(this.id, winAbjectId, WINDOW_INTERFACE, 'removeChild', { widgetId: abjectId })
          );
        } catch {
          // Window may be gone
        }
      }
    }

    // Destroy the widget
    try {
      await this.send(request(this.id, abjectId, WIDGET_INTERFACE, 'destroy', {}));
    } catch {
      // Widget may be gone
    }

    this.shimWidgetMap.delete(widgetId);
    this.widgetIdToShimId.delete(abjectId);
    this.widgetToWindowShimId.delete(abjectId);
    this.spawnedWidgets.delete(abjectId);

    return true;
  }

  // ── Shim: getWidgetValue ──────────────────────────────────────────────

  private async getWidgetValue(widgetId: string): Promise<string> {
    const abjectId = this.shimWidgetMap.get(widgetId);
    if (!abjectId) return '';

    try {
      return await this.request<string>(
        request(this.id, abjectId, WIDGET_INTERFACE, 'getValue', {})
      );
    } catch {
      return '';
    }
  }
}

// Well-known WidgetManager ID
export const WIDGET_MANAGER_ID = 'abjects:widget-manager' as AbjectId;
